const FOOD_CATEGORIES = ["side","protein","vegetables","butter","oil","dessert"];

function validateFoodDBItems(foods){
  const errors = [];
  if(!Array.isArray(foods)) return { ok: false, errors: ["foodDB must be an array"], count: 0 };
  const ids = new Set();
  foods.forEach((food, index) => {
    const label = "item #" + (index + 1);
    if(!food || typeof food !== "object"){ errors.push(label + ": must be an object"); return; }
    if(typeof food.id !== "string" || !food.id.trim()) errors.push(label + ": missing id");
    else if(ids.has(food.id)) errors.push(label + ': duplicate id "' + food.id + '"');
    else ids.add(food.id);
    if(typeof food.name !== "string" || !food.name.trim()) errors.push(label + ": missing name");
    if(!FOOD_CATEGORIES.includes(food.category)) errors.push(label + ' "' + food.name + '": invalid category "' + food.category + '"');
    if(!Array.isArray(food.aliases)) errors.push(label + ' "' + food.name + '": aliases must be an array');
    ["kcal", "protein", "fat", "carbs"].forEach(field => {
      if(typeof food[field] !== "number" || !Number.isFinite(food[field]) || food[field] < 0){
        errors.push(label + ' "' + food.name + '": invalid ' + field);
      }
    });
    if(food.source !== undefined && typeof food.source !== "string") errors.push(label + ' "' + food.name + '": invalid source');
  });
  return { ok: errors.length === 0, errors, count: foods.length };
}

window.validateFoodDB = function(){
  return validateFoodDBItems(window.foodDB);
};

window.foodDB = [
  { id: "ogurets", name: "огурец", aliases: ["огурцы","огурец свежий"], category: "vegetables", kcal: 15, protein: 0.8, fat: 0.1, carbs: 3 },
  { id: "pomidor", name: "помидор", aliases: ["томат","помидоры"], category: "vegetables", kcal: 20, protein: 1, fat: 0.2, carbs: 4 },
  { id: "tomaty", name: "томаты", aliases: ["томаты свежие"], category: "vegetables", kcal: 20, protein: 1, fat: 0.2, carbs: 4 },
  { id: "kartofel", name: "картофель", aliases: ["картошка","картофель сырой"], category: "vegetables", kcal: 77, protein: 2, fat: 0.1, carbs: 17 },
  { id: "morkov", name: "морковь", aliases: ["морковка"], category: "vegetables", kcal: 41, protein: 0.9, fat: 0.2, carbs: 9.6 },
  { id: "svekla", name: "свекла", aliases: ["свекла сырая"], category: "vegetables", kcal: 43, protein: 1.6, fat: 0.2, carbs: 9.6 },
  { id: "kapusta_belokochannaya", name: "капуста белокочанная", aliases: ["белокочанная капуста","капуста","капуста белая"], category: "vegetables", kcal: 27, protein: 1.8, fat: 0.1, carbs: 6 },
  { id: "kapusta_tsvetnaya", name: "капуста цветная", aliases: ["цветная капуста"], category: "vegetables", kcal: 25, protein: 1.9, fat: 0.3, carbs: 5 },
  { id: "brokkoli", name: "брокколи", aliases: ["брокколи свежая","капуста брокколи"], category: "vegetables", kcal: 34, protein: 2.8, fat: 0.4, carbs: 6.6 },
  { id: "kabachok", name: "кабачок", aliases: ["кабачки"], category: "vegetables", kcal: 24, protein: 0.6, fat: 0.3, carbs: 4.6 },
  { id: "baklazhan", name: "баклажан", aliases: ["баклажаны"], category: "vegetables", kcal: 25, protein: 1, fat: 0.2, carbs: 5.9 },
  { id: "perets_bolgarskiy", name: "перец болгарский", aliases: ["болгарский перец","перец сладкий","сладкий перец"], category: "vegetables", kcal: 27, protein: 1, fat: 0.2, carbs: 6 },
  { id: "luk_repchatyy", name: "лук репчатый", aliases: ["лук","репчатый лук"], category: "vegetables", kcal: 40, protein: 1.1, fat: 0.1, carbs: 9.3 },
  { id: "chesnok", name: "чеснок", aliases: ["чеснок свежий"], category: "vegetables", kcal: 149, protein: 6.4, fat: 0.5, carbs: 33.1 },
  { id: "redis", name: "редис", aliases: ["редиска"], category: "vegetables", kcal: 16, protein: 0.7, fat: 0.1, carbs: 3.4 },
  { id: "tykva", name: "тыква", aliases: ["тыква свежая"], category: "vegetables", kcal: 26, protein: 1, fat: 0.1, carbs: 6.5 },
  { id: "salat_listovoy", name: "салат листовой", aliases: ["латук","салат","листовой салат","зеленый салат"], category: "vegetables", kcal: 15, protein: 1.4, fat: 0.2, carbs: 2.9 },
  { id: "shpinat", name: "шпинат", aliases: ["шпинат листовой","шпинат свежий"], category: "vegetables", kcal: 23, protein: 2.9, fat: 0.4, carbs: 3.6 },
  { id: "ukrop", name: "укроп", aliases: ["укроп свежий","укроп зелень"], category: "vegetables", kcal: 43, protein: 3.5, fat: 1.1, carbs: 7 },
  { id: "petrushka", name: "петрушка", aliases: ["петрушка свежая","петрушка зелень"], category: "vegetables", kcal: 36, protein: 3, fat: 0.8, carbs: 6.3 },
  { id: "yabloko", name: "яблоко", aliases: ["яблоки","яблоко свежее"], category: "dessert", kcal: 52, protein: 0.3, fat: 0.2, carbs: 14 },
  { id: "banan", name: "банан", aliases: ["бананы"], category: "dessert", kcal: 89, protein: 1.1, fat: 0.3, carbs: 23 },
  { id: "grusha", name: "груша", aliases: ["груши"], category: "dessert", kcal: 57, protein: 0.4, fat: 0.1, carbs: 15 },
  { id: "apelsin", name: "апельсин", aliases: ["апельсины"], category: "dessert", kcal: 47, protein: 0.9, fat: 0.1, carbs: 12 },
  { id: "mandarin", name: "мандарин", aliases: ["мандарины","мандаринка"], category: "dessert", kcal: 53, protein: 0.8, fat: 0.3, carbs: 13.3 },
  { id: "limon", name: "лимон", aliases: ["лимоны"], category: "dessert", kcal: 29, protein: 1.1, fat: 0.3, carbs: 9.3 },
  { id: "kivi", name: "киви", aliases: ["киви фрукт"], category: "dessert", kcal: 61, protein: 1.1, fat: 0.5, carbs: 15 },
  { id: "vinograd", name: "виноград", aliases: ["виноград свежий"], category: "dessert", kcal: 69, protein: 0.7, fat: 0.2, carbs: 18 },
  { id: "arbuz", name: "арбуз", aliases: ["арбуз свежий"], category: "dessert", kcal: 30, protein: 0.6, fat: 0.2, carbs: 7.6 },
  { id: "dynya", name: "дыня", aliases: ["дыня свежая"], category: "dessert", kcal: 34, protein: 0.8, fat: 0.2, carbs: 8.2 },
  { id: "persik", name: "персик", aliases: ["персики"], category: "dessert", kcal: 39, protein: 0.9, fat: 0.3, carbs: 10 },
  { id: "nektarin", name: "нектарин", aliases: ["нектарины"], category: "dessert", kcal: 44, protein: 1.1, fat: 0.3, carbs: 11 },
  { id: "sliva", name: "слива", aliases: ["сливы"], category: "dessert", kcal: 46, protein: 0.7, fat: 0.3, carbs: 11.4 },
  { id: "abrikos", name: "абрикос", aliases: ["абрикосы"], category: "dessert", kcal: 48, protein: 1.4, fat: 0.4, carbs: 11.1 },
  { id: "granat", name: "гранат", aliases: ["гранаты","гранат свежий"], category: "dessert", kcal: 83, protein: 1.7, fat: 1.2, carbs: 18.7 },
  { id: "ananas", name: "ананас", aliases: ["ананасы"], category: "dessert", kcal: 50, protein: 0.5, fat: 0.1, carbs: 13.1 },
  { id: "mango", name: "манго", aliases: ["манго фрукт"], category: "dessert", kcal: 60, protein: 0.8, fat: 0.4, carbs: 15 },
  { id: "hurma", name: "хурма", aliases: ["хурмы"], category: "dessert", kcal: 67, protein: 0.5, fat: 0.4, carbs: 15.3 },
  { id: "klubnika", name: "клубника", aliases: ["клубника свежая"], category: "dessert", kcal: 32, protein: 0.7, fat: 0.3, carbs: 7.7 },
  { id: "malina", name: "малина", aliases: ["малина свежая"], category: "dessert", kcal: 52, protein: 1.2, fat: 0.7, carbs: 12 },
  { id: "chernika", name: "черника", aliases: ["черника свежая"], category: "dessert", kcal: 57, protein: 0.7, fat: 0.3, carbs: 14.5 },
  { id: "smorodina", name: "смородина", aliases: ["смородина свежая"], category: "dessert", kcal: 63, protein: 1.4, fat: 0.4, carbs: 15.4 },
  { id: "vishnya", name: "вишня", aliases: ["вишни"], category: "dessert", kcal: 50, protein: 1, fat: 0.3, carbs: 12.2 },
  { id: "chereshnya", name: "черешня", aliases: ["черешни"], category: "dessert", kcal: 63, protein: 1.1, fat: 0.2, carbs: 16 },
  { id: "klyukva", name: "клюква", aliases: ["клюква свежая"], category: "dessert", kcal: 46, protein: 0.4, fat: 0.1, carbs: 12.2 },
  { id: "izyum", name: "изюм", aliases: ["виноград сушеный"], category: "dessert", kcal: 299, protein: 3.1, fat: 0.5, carbs: 79.2 },
  { id: "kuraga", name: "курага", aliases: ["абрикос сушеный","абрикосы сушеные"], category: "dessert", kcal: 241, protein: 3.4, fat: 0.5, carbs: 63 },
  { id: "chernosliv", name: "чернослив", aliases: ["слива сушеная","слива сушёная"], category: "dessert", kcal: 240, protein: 2.2, fat: 0.4, carbs: 64 },
  { id: "finiki", name: "финики", aliases: ["финик"], category: "dessert", kcal: 282, protein: 2.5, fat: 0.4, carbs: 75 },
  { id: "inzhir_sushenyy", name: "инжир сушеный", aliases: ["инжир сушёный","сушеный инжир"], category: "dessert", kcal: 249, protein: 3.3, fat: 0.9, carbs: 64 },
  { id: "hleb_belyy", name: "хлеб белый", aliases: ["хлеб пшеничный","белый хлеб"], category: "side", kcal: 265, protein: 8, fat: 3.2, carbs: 49 },
  { id: "hleb_rzhanoy", name: "хлеб ржаной", aliases: ["черный хлеб","хлеб черный"], category: "side", kcal: 210, protein: 6.6, fat: 1.2, carbs: 43 },
  { id: "hleb_tselnozernovoy", name: "хлеб цельнозерновой", aliases: ["цельнозерновой хлеб","цельнозерновый хлеб","цельнозерновый"], category: "side", kcal: 247, protein: 13, fat: 4.2, carbs: 41 },
  { id: "baton", name: "батон", aliases: ["батон нарезной"], category: "side", kcal: 263, protein: 7.5, fat: 2.9, carbs: 51 },
  { id: "lavash", name: "лаваш", aliases: ["лаваш тонкий","тонкий лаваш"], category: "side", kcal: 275, protein: 9.1, fat: 1.2, carbs: 56 },
  { id: "suhari", name: "сухари", aliases: [], category: "side", kcal: 350, protein: 11, fat: 1.5, carbs: 73 },
  { id: "galety", name: "галеты", aliases: [], category: "side", kcal: 393, protein: 9.7, fat: 10.2, carbs: 65 },
  { id: "baranki", name: "баранки", aliases: [], category: "side", kcal: 336, protein: 10, fat: 1.3, carbs: 69 },
  { id: "bulochka", name: "булочка", aliases: [], category: "side", kcal: 310, protein: 8, fat: 6, carbs: 56 },
  { id: "kruassan", name: "круассан", aliases: [], category: "side", kcal: 406, protein: 8.2, fat: 21, carbs: 45 },
  { id: "muka_pshenichnaya", name: "мука пшеничная", aliases: [], category: "side", kcal: 364, protein: 10.3, fat: 1, carbs: 76 },
  { id: "muka_rzhanaya", name: "мука ржаная", aliases: [], category: "side", kcal: 325, protein: 9, fat: 1.7, carbs: 68 },
  { id: "ovsyanye_hlopya", name: "овсяные хлопья", aliases: ["овсянка","геркулес","овсяные хлопья"], category: "side", kcal: 366, protein: 11.9, fat: 7.2, carbs: 69 },
  { id: "buckwheat_boiled", name: "гречка вареная", aliases: ["гречка","гречневая каша","гречка вареная"], category: "side", kcal: 110, protein: 3.6, fat: 1.1, carbs: 21 },
  { id: "buckwheat_dry", name: "гречка сухая", aliases: ["гречка","гречневая крупа","гречка ядрица"], category: "side", kcal: 343, protein: 13.3, fat: 3.4, carbs: 72 },
  { id: "rice_boiled", name: "рис вареный", aliases: ["рис","рис белый вареный","вареный рис"], category: "side", kcal: 130, protein: 2.7, fat: 0.3, carbs: 28 },
  { id: "rice_dry", name: "рис сухой", aliases: ["рис","рис белый сухой","белый рис"], category: "side", kcal: 365, protein: 7.1, fat: 0.7, carbs: 80 },
  { id: "pasta_boiled", name: "макароны вареные", aliases: ["макароны","паста","вареные макароны","паста вареная"], category: "side", kcal: 131, protein: 5, fat: 1.1, carbs: 25 },
  { id: "pasta_dry", name: "макароны сухие", aliases: ["макароны","паста","сухие макароны","паста сухая"], category: "side", kcal: 350, protein: 12, fat: 1.5, carbs: 72 },
  { id: "perlovka_varenaya", name: "перловка вареная", aliases: ["перловка","перловая каша"], category: "side", kcal: 109, protein: 3.1, fat: 0.4, carbs: 22 },
  { id: "psheno_varenoe", name: "пшено вареное", aliases: ["пшено","пшенная каша"], category: "side", kcal: 119, protein: 3.5, fat: 1, carbs: 23.7 },
  { id: "bulgur_varenyy", name: "булгур вареный", aliases: ["булгур","булгур вареный"], category: "side", kcal: 83, protein: 3.1, fat: 0.2, carbs: 18.6 },
  { id: "kinoa_varenaya", name: "киноа вареная", aliases: ["киноа"], category: "side", kcal: 120, protein: 4.4, fat: 1.9, carbs: 21.3 },
  { id: "manka_varenaya", name: "манка вареная", aliases: ["манка","манная каша"], category: "side", kcal: 80, protein: 2.5, fat: 0.2, carbs: 16.8 },
  { id: "kukuruznaya_kasha", name: "кукурузная каша", aliases: ["кукурузная каша на воде"], category: "side", kcal: 86, protein: 2.3, fat: 0.3, carbs: 19 },
  { id: "moloko_2_5", name: "молоко 2.5%", aliases: ["молоко 2,5%","молоко"], category: "protein", kcal: 52, protein: 2.8, fat: 2.5, carbs: 4.7 },
  { id: "moloko_3_2", name: "молоко 3.2%", aliases: ["молоко 3,2%"], category: "protein", kcal: 60, protein: 3, fat: 3.2, carbs: 4.7 },
  { id: "kefir_1", name: "кефир 1%", aliases: ["кефир 1 процент"], category: "protein", kcal: 40, protein: 3, fat: 1, carbs: 4 },
  { id: "kefir_2_5", name: "кефир 2.5%", aliases: ["кефир 2,5%"], category: "protein", kcal: 53, protein: 3, fat: 2.5, carbs: 4 },
  { id: "ryazhenka", name: "ряженка", aliases: [], category: "protein", kcal: 67, protein: 2.8, fat: 4, carbs: 4.2 },
  { id: "yogurt_naturalnyy", name: "йогурт натуральный", aliases: ["йогурт","натуральный йогурт"], category: "protein", kcal: 61, protein: 3.5, fat: 3.3, carbs: 4.7 },
  { id: "tvorog_5", name: "творог 5%", aliases: ["творог","творог 5 процентов"], category: "protein", kcal: 121, protein: 17, fat: 5, carbs: 2 },
  { id: "tvorog_9", name: "творог 9%", aliases: ["творог 9 процентов"], category: "protein", kcal: 159, protein: 16.7, fat: 9, carbs: 2 },
  { id: "smetana_10", name: "сметана 10%", aliases: ["сметана 10 процентов"], category: "protein", kcal: 119, protein: 2.7, fat: 10, carbs: 3.9 },
  { id: "smetana_20", name: "сметана 20%", aliases: ["сметана 20 процентов"], category: "protein", kcal: 206, protein: 2.5, fat: 20, carbs: 3.4 },
  { id: "syr_rossiyskiy", name: "сыр российский", aliases: ["российский сыр","сыр российский"], category: "protein", kcal: 363, protein: 24, fat: 29.5, carbs: 0.3 },
  { id: "syr_gauda", name: "сыр гауда", aliases: ["гауда","сыр гауда"], category: "protein", kcal: 356, protein: 25, fat: 27, carbs: 2.2 },
  { id: "syr_motsarella", name: "сыр моцарелла", aliases: ["моцарелла","сыр моцарелла"], category: "protein", kcal: 280, protein: 28, fat: 17, carbs: 3.1 },
  { id: "syr_feta", name: "сыр фета", aliases: ["фета","сыр фета"], category: "protein", kcal: 264, protein: 14, fat: 21, carbs: 4.1 },
  { id: "syr_plavlenyy", name: "сыр плавленый", aliases: ["плавленый сыр"], category: "protein", kcal: 257, protein: 16.8, fat: 19, carbs: 3.5 },
  { id: "maslo_slivochnoe", name: "масло сливочное", aliases: [], category: "butter", kcal: 748, protein: 0.5, fat: 82.5, carbs: 0.8 },
  { id: "butter_725", name: "масло сливочное 72,5%", aliases: [], category: "butter", kcal: 662, protein: 0.8, fat: 72.5, carbs: 1.3 },
  { id: "butter_825", name: "масло сливочное 82,5%", aliases: [], category: "butter", kcal: 748, protein: 0.5, fat: 82.5, carbs: 0.8 },
  { id: "slivki_10", name: "сливки 10%", aliases: ["сливки 10 процентов"], category: "protein", kcal: 118, protein: 3, fat: 10, carbs: 4 },
  { id: "slivki_20", name: "сливки 20%", aliases: ["сливки 20 процентов"], category: "protein", kcal: 206, protein: 2.8, fat: 20, carbs: 3.7 },
  { id: "morozhenoe_plombir", name: "мороженое пломбир", aliases: ["мороженое"], category: "dessert", kcal: 232, protein: 3.7, fat: 15, carbs: 20.4 },
  { id: "sguschenka", name: "сгущенка", aliases: ["сгущёнка","сгущенка","сгущённое молоко","сгущенное молоко"], category: "dessert", kcal: 321, protein: 7.2, fat: 8.5, carbs: 56 },
  { id: "egg_chicken", name: "яйцо куриное", aliases: ["яйцо","куриное яйцо"], category: "protein", kcal: 155, protein: 13, fat: 11, carbs: 1.1 },
  { id: "belok_yaytsa", name: "белок яйца", aliases: [], category: "protein", kcal: 52, protein: 10.9, fat: 0.2, carbs: 0.7 },
  { id: "zheltok_yaytsa", name: "желток яйца", aliases: [], category: "protein", kcal: 322, protein: 15.9, fat: 26.5, carbs: 3.6 },
  { id: "omlet", name: "омлет", aliases: ["омлет классический"], category: "protein", kcal: 154, protein: 10.6, fat: 11, carbs: 2 },
  { id: "yaichnitsa", name: "яичница", aliases: ["яичница глазунья","глазунья"], category: "protein", kcal: 196, protein: 13.6, fat: 15.3, carbs: 0.8 },
  { id: "chicken_breast", name: "куриная грудка", aliases: ["грудка","грудка курицы","куриная грудка филе","филе курицы"], category: "protein", kcal: 165, protein: 31, fat: 3.6, carbs: 0 },
  { id: "kurinoe_bedro", name: "куриное бедро", aliases: ["бедро курицы","куриные бедра"], category: "protein", kcal: 209, protein: 26, fat: 10.9, carbs: 0 },
  { id: "kuritsa_varenaya", name: "курица вареная", aliases: ["вареная курица"], category: "protein", kcal: 170, protein: 25, fat: 7, carbs: 0 },
  { id: "indeyka", name: "индейка", aliases: ["мясо индейки","индейка"], category: "protein", kcal: 135, protein: 29, fat: 1, carbs: 0 },
  { id: "govyadina", name: "говядина", aliases: ["мясо говядины"], category: "protein", kcal: 250, protein: 26, fat: 15, carbs: 0 },
  { id: "telyatina", name: "телятина", aliases: [], category: "protein", kcal: 172, protein: 24, fat: 8, carbs: 0 },
  { id: "svinina", name: "свинина", aliases: ["мясо свинины"], category: "protein", kcal: 297, protein: 25.7, fat: 20.8, carbs: 0 },
  { id: "baranina", name: "баранина", aliases: [], category: "protein", kcal: 294, protein: 25, fat: 21, carbs: 0 },
  { id: "farsh_govyazhiy", name: "фарш говяжий", aliases: ["фарш говядины"], category: "protein", kcal: 254, protein: 17.2, fat: 20, carbs: 0 },
  { id: "farsh_kurinyy", name: "фарш куриный", aliases: ["фарш курицы","курица фарш"], category: "protein", kcal: 143, protein: 17.4, fat: 8.1, carbs: 0 },
  { id: "pechen_kurinaya", name: "печень куриная", aliases: ["куриная печень"], category: "protein", kcal: 137, protein: 20.4, fat: 5.9, carbs: 0.7 },
  { id: "pechen_govyazhya", name: "печень говяжья", aliases: ["говяжья печень"], category: "protein", kcal: 135, protein: 20, fat: 3.6, carbs: 4 },
  { id: "vetchina", name: "ветчина", aliases: ["ветчина куриная","ветчина свиная"], category: "protein", kcal: 145, protein: 21, fat: 6, carbs: 1 },
  { id: "kolbasa_varenaya", name: "колбаса вареная", aliases: [], category: "protein", kcal: 257, protein: 12.8, fat: 22.2, carbs: 1.5 },
  { id: "kolbasa_kopchenaya", name: "колбаса копченая", aliases: [], category: "protein", kcal: 507, protein: 24, fat: 45, carbs: 0.5 },
  { id: "sosiski", name: "сосиски", aliases: [], category: "protein", kcal: 266, protein: 11, fat: 23.9, carbs: 1.6 },
  { id: "sardelki", name: "сардельки", aliases: [], category: "protein", kcal: 332, protein: 10, fat: 31, carbs: 1.5 },
  { id: "bekon", name: "бекон", aliases: ["бекон копченый"], category: "protein", kcal: 541, protein: 37, fat: 42, carbs: 1.4 },
  { id: "salo", name: "сало", aliases: [], category: "protein", kcal: 797, protein: 2.4, fat: 89, carbs: 0 },
  { id: "pashtet", name: "паштет", aliases: [], category: "protein", kcal: 319, protein: 11, fat: 28, carbs: 3 },
  { id: "losos", name: "лосось", aliases: ["семга","лосось"], category: "protein", kcal: 208, protein: 20, fat: 13, carbs: 0 },
  { id: "semga", name: "семга", aliases: ["лосось","семга"], category: "protein", kcal: 208, protein: 20, fat: 13, carbs: 0 },
  { id: "forel", name: "форель", aliases: ["радужная форель"], category: "protein", kcal: 148, protein: 20.8, fat: 6.6, carbs: 0 },
  { id: "tunets", name: "тунец", aliases: ["тунец свежий"], category: "protein", kcal: 132, protein: 28, fat: 1.3, carbs: 0 },
  { id: "treska", name: "треска", aliases: ["треска филе"], category: "protein", kcal: 82, protein: 18, fat: 0.7, carbs: 0 },
  { id: "mintay", name: "минтай", aliases: [], category: "protein", kcal: 72, protein: 16, fat: 0.9, carbs: 0 },
  { id: "hek", name: "хек", aliases: ["хек филе"], category: "protein", kcal: 86, protein: 16.6, fat: 2.2, carbs: 0 },
  { id: "skumbriya", name: "скумбрия", aliases: [], category: "protein", kcal: 205, protein: 19, fat: 14, carbs: 0 },
  { id: "seld", name: "сельдь", aliases: ["сельдь свежая"], category: "protein", kcal: 217, protein: 19.8, fat: 15.4, carbs: 0 },
  { id: "sardina", name: "сардина", aliases: [], category: "protein", kcal: 208, protein: 25, fat: 11, carbs: 0 },
  { id: "krevetki", name: "креветки", aliases: ["креветка"], category: "protein", kcal: 99, protein: 24, fat: 0.3, carbs: 0.2 },
  { id: "kalmar", name: "кальмар", aliases: ["кальмары"], category: "protein", kcal: 92, protein: 15.6, fat: 1.4, carbs: 3.1 },
  { id: "midii", name: "мидии", aliases: ["мидия"], category: "protein", kcal: 86, protein: 12, fat: 2.2, carbs: 3.7 },
  { id: "ikra_krasnaya", name: "икра красная", aliases: ["красная икра"], category: "protein", kcal: 250, protein: 31, fat: 13, carbs: 1 },
  { id: "krabovye_palochki", name: "крабовые палочки", aliases: ["крабовые палочки","сурими"], category: "protein", kcal: 95, protein: 7, fat: 1, carbs: 15 },
  { id: "fasol_varenaya", name: "фасоль вареная", aliases: [], category: "side", kcal: 127, protein: 8.7, fat: 0.5, carbs: 22.8 },
  { id: "goroh_varenyy", name: "горох вареный", aliases: [], category: "side", kcal: 118, protein: 8.3, fat: 0.4, carbs: 21.1 },
  { id: "chechevitsa_varenaya", name: "чечевица вареная", aliases: [], category: "side", kcal: 116, protein: 9, fat: 0.4, carbs: 20 },
  { id: "nut_varenyy", name: "нут вареный", aliases: [], category: "side", kcal: 164, protein: 8.9, fat: 2.6, carbs: 27.4 },
  { id: "kukuruza_varenaya", name: "кукуруза вареная", aliases: [], category: "side", kcal: 96, protein: 3.4, fat: 1.5, carbs: 21 },
  { id: "zelenyy_goroshek", name: "зеленый горошек", aliases: ["горошек","горошек зеленый","зеленый горошек свежий"], category: "vegetables", kcal: 81, protein: 5.4, fat: 0.4, carbs: 14.5 },
  { id: "fasol_struchkovaya", name: "фасоль стручковая", aliases: ["стручковая фасоль","фасоль стручковая свежая","стручковая фасоль свежая"], category: "vegetables", kcal: 31, protein: 1.8, fat: 0.1, carbs: 7 },
  { id: "soevyy_syr_tofu", name: "соевый сыр тофу", aliases: ["тофу","соевый сыр"], category: "protein", kcal: 76, protein: 8, fat: 4.8, carbs: 1.9 },
  { id: "soevoe_moloko", name: "соевое молоко", aliases: [], category: "protein", kcal: 54, protein: 3.3, fat: 1.8, carbs: 6.3 },
  { id: "humus", name: "хумус", aliases: [], category: "protein", kcal: 166, protein: 7.9, fat: 9.6, carbs: 14.3 },
  { id: "mindal", name: "миндаль", aliases: ["миндаль орех","орех миндаль"], category: "dessert", kcal: 579, protein: 21, fat: 50, carbs: 22 },
  { id: "gretskiy_oreh", name: "грецкий орех", aliases: ["грецкий","орех грецкий"], category: "dessert", kcal: 654, protein: 15.2, fat: 65.2, carbs: 13.7 },
  { id: "funduk", name: "фундук", aliases: ["фундук орех","лещина"], category: "dessert", kcal: 628, protein: 15, fat: 61, carbs: 17 },
  { id: "keshyu", name: "кешью", aliases: ["кешью орех","орех кешью"], category: "dessert", kcal: 553, protein: 18, fat: 44, carbs: 30 },
  { id: "arahis", name: "арахис", aliases: ["земляной орех","арахис жареный"], category: "dessert", kcal: 567, protein: 25.8, fat: 49.2, carbs: 16.1 },
  { id: "fistashki", name: "фисташки", aliases: ["фисташка","фисташки орех"], category: "dessert", kcal: 562, protein: 20, fat: 45, carbs: 28 },
  { id: "semechki_podsolnechnye", name: "семечки подсолнечные", aliases: ["семечки","подсолнечные семечки"], category: "dessert", kcal: 584, protein: 20.8, fat: 51.5, carbs: 20 },
  { id: "semena_tykvy", name: "семена тыквы", aliases: ["тыквенные семечки","семечки тыквы"], category: "dessert", kcal: 559, protein: 30.2, fat: 49, carbs: 10.7 },
  { id: "semena_lna", name: "семена льна", aliases: ["лен семена","льняное семя"], category: "dessert", kcal: 534, protein: 18.3, fat: 42.2, carbs: 28.9 },
  { id: "semena_chia", name: "семена чиа", aliases: ["чиа","семя чиа"], category: "dessert", kcal: 486, protein: 16.5, fat: 30.7, carbs: 42.1 },
  { id: "olive_oil", name: "масло оливковое", aliases: [], category: "oil", kcal: 884, protein: 0, fat: 100, carbs: 0 },
  { id: "sunflower_oil", name: "масло подсолнечное", aliases: [], category: "oil", kcal: 884, protein: 0, fat: 100, carbs: 0 },
  { id: "flax_oil", name: "масло льняное", aliases: [], category: "oil", kcal: 884, protein: 0, fat: 100, carbs: 0 },
  { id: "coconut_oil", name: "масло кокосовое", aliases: [], category: "oil", kcal: 862, protein: 0, fat: 100, carbs: 0 },
  { id: "mayonez", name: "майонез классический", aliases: ["майонез"], category: "dessert", kcal: 680, protein: 1, fat: 75, carbs: 2.6 },
  { id: "ketchup", name: "кетчуп", aliases: ["кетчуп томатный"], category: "dessert", kcal: 112, protein: 1.7, fat: 0.2, carbs: 25.8 },
  { id: "gorchitsa", name: "горчица", aliases: ["горчица столовая"], category: "dessert", kcal: 66, protein: 4.4, fat: 4, carbs: 5 },
  { id: "soevyy_sous", name: "соевый соус", aliases: ["соевый","соус соевый"], category: "dessert", kcal: 53, protein: 8.1, fat: 0.6, carbs: 4.9 },
  { id: "med", name: "мед", aliases: ["мёд"], category: "dessert", kcal: 304, protein: 0.3, fat: 0, carbs: 82.4 },
  { id: "sahar", name: "сахар белый", aliases: ["сахар"], category: "dessert", kcal: 387, protein: 0, fat: 0, carbs: 100 },
  { id: "varene", name: "варенье", aliases: ["варенья"], category: "dessert", kcal: 260, protein: 0.3, fat: 0.1, carbs: 68 },
  { id: "shokolad_molochnyy", name: "шоколад молочный", aliases: ["шоколад"], category: "dessert", kcal: 535, protein: 7.7, fat: 30, carbs: 59 },
  { id: "shokolad_temnyy", name: "шоколад темный", aliases: ["шоколад тёмный","тёмный шоколад","темный шоколад"], category: "dessert", kcal: 546, protein: 4.9, fat: 31, carbs: 61 },
  { id: "pechene", name: "печенье", aliases: ["печенье сахарное"], category: "dessert", kcal: 450, protein: 7, fat: 18, carbs: 66 },
  { id: "vafli", name: "вафли", aliases: ["вафля"], category: "dessert", kcal: 520, protein: 5.5, fat: 30, carbs: 60 },
  { id: "zefir", name: "зефир", aliases: ["зефирки"], category: "dessert", kcal: 326, protein: 0.8, fat: 0.1, carbs: 79.8 },
  { id: "marmelad", name: "мармелад", aliases: ["мармеладки"], category: "dessert", kcal: 321, protein: 0.1, fat: 0, carbs: 79.4 },
  { id: "halva", name: "халва", aliases: ["халва подсолнечная"], category: "dessert", kcal: 516, protein: 12.7, fat: 29.9, carbs: 50.6 },
  { id: "tort_biskvitnyy", name: "торт бисквитный", aliases: [], category: "dessert", kcal: 350, protein: 5, fat: 15, carbs: 50 },
  { id: "pirozhnoe", name: "пирожное", aliases: [], category: "dessert", kcal: 400, protein: 5, fat: 22, carbs: 47 },
  { id: "myusli", name: "мюсли", aliases: [], category: "dessert", kcal: 340, protein: 9, fat: 5, carbs: 66 },
  { id: "borsch", name: "борщ", aliases: ["борщ красный","борщ домашний"], category: "side", kcal: 57, protein: 3.8, fat: 2.9, carbs: 4.3 },
  { id: "schi", name: "щи", aliases: ["щи капустные","щи из свежей капусты"], category: "side", kcal: 35, protein: 2, fat: 1.5, carbs: 4 },
  { id: "sup_kurinyy", name: "суп куриный", aliases: ["куриный суп","суп с курицей"], category: "side", kcal: 45, protein: 4, fat: 2, carbs: 3 },
  { id: "sup_gorohovyy", name: "суп гороховый", aliases: [], category: "side", kcal: 66, protein: 4.4, fat: 2.4, carbs: 8.9 },
  { id: "okroshka", name: "окрошка", aliases: ["окрошка на квасе","окрошка классическая"], category: "side", kcal: 60, protein: 3.5, fat: 3, carbs: 5 },
  { id: "plov", name: "плов", aliases: ["плов с мясом","плов узбекский"], category: "side", kcal: 180, protein: 6, fat: 7, carbs: 24 },
  { id: "grechka_s_kuritsey", name: "гречка с курицей", aliases: [], category: "side", kcal: 135, protein: 9, fat: 3.5, carbs: 17 },
  { id: "makarony_s_syrom", name: "макароны с сыром", aliases: [], category: "side", kcal: 220, protein: 8, fat: 9, carbs: 27 },
  { id: "pelmeni", name: "пельмени", aliases: ["пельмени домашние","пельмени мясные"], category: "side", kcal: 275, protein: 11, fat: 13, carbs: 29 },
  { id: "vareniki_s_kartoshkoy", name: "вареники с картошкой", aliases: ["вареники с картофелем","вареники картофель"], category: "side", kcal: 185, protein: 5, fat: 3, carbs: 35 },
  { id: "kotleta_kurinaya", name: "котлета куриная", aliases: ["котлета из курицы","куриная котлета"], category: "protein", kcal: 190, protein: 17, fat: 10, carbs: 8 },
  { id: "kotleta_myasnaya", name: "котлета мясная", aliases: ["котлета домашняя","котлета мясная домашняя"], category: "protein", kcal: 240, protein: 15, fat: 17, carbs: 8 },
  { id: "golubtsy", name: "голубцы", aliases: ["голубцы с мясом","голубцы с фаршем"], category: "protein", kcal: 143, protein: 7, fat: 8, carbs: 11 },
  { id: "tefteli", name: "тефтели", aliases: ["тефтели в томатном соусе","тефтели домашние"], category: "protein", kcal: 220, protein: 12, fat: 14, carbs: 10 },
  { id: "omlet_s_syrom", name: "омлет с сыром", aliases: ["омлет сырный"], category: "protein", kcal: 210, protein: 14, fat: 16, carbs: 2 },
  { id: "salat_olive", name: "салат оливье", aliases: [], category: "vegetables", kcal: 198, protein: 5, fat: 16, carbs: 8 },
  { id: "salat_vinegret", name: "салат винегрет", aliases: [], category: "vegetables", kcal: 130, protein: 2, fat: 8, carbs: 14 },
  { id: "salat_tsezar", name: "салат цезарь", aliases: [], category: "vegetables", kcal: 190, protein: 9, fat: 14, carbs: 7 },
  { id: "salat_grecheskiy", name: "салат греческий", aliases: [], category: "vegetables", kcal: 120, protein: 4, fat: 9, carbs: 6 },
  { id: "pyure_kartofelnoe", name: "пюре картофельное", aliases: [], category: "side", kcal: 90, protein: 2, fat: 3, carbs: 15 },
  { id: "kartofel_zharenyy", name: "картофель жареный", aliases: [], category: "side", kcal: 192, protein: 2.8, fat: 9.5, carbs: 23.4 },
  { id: "kartofel_fri", name: "картофель фри", aliases: ["фри","картошка фри"], category: "side", kcal: 312, protein: 3.4, fat: 15, carbs: 41 },
  { id: "syrniki", name: "сырники", aliases: ["сырники творожные","сырнички"], category: "side", kcal: 220, protein: 14, fat: 10, carbs: 18 },
  { id: "bliny", name: "блины", aliases: ["блинчики","блины тонкие"], category: "side", kcal: 227, protein: 6, fat: 10, carbs: 28 },
  { id: "oladi", name: "оладьи", aliases: ["оладушки"], category: "side", kcal: 230, protein: 6, fat: 9, carbs: 32 },
  { id: "pitstsa_margarita", name: "пицца маргарита", aliases: ["маргарита","пицца маргарита"], category: "side", kcal: 266, protein: 11, fat: 10, carbs: 33 },
  { id: "pitstsa_pepperoni", name: "пицца пепперони", aliases: ["пепперони","пицца пепперони"], category: "side", kcal: 298, protein: 12, fat: 14, carbs: 31 },
  { id: "burger", name: "бургер", aliases: ["бургер классический","классический бургер","гамбургер"], category: "side", kcal: 295, protein: 17, fat: 14, carbs: 24 },
  { id: "shaurma", name: "шаурма", aliases: ["шаверма","шаурма куриная"], category: "side", kcal: 210, protein: 11, fat: 10, carbs: 20 },
  { id: "hot_dog", name: "хот-дог", aliases: ["хот дог","хотдог"], category: "side", kcal: 290, protein: 10, fat: 17, carbs: 24 },
  { id: "chay_bez_sahara", name: "чай без сахара", aliases: ["чёрный чай","чай чёрный","чай черный","черный чай"], category: "dessert", kcal: 1, protein: 0, fat: 0, carbs: 0 },
  { id: "kofe_bez_sahara", name: "кофе без сахара", aliases: ["кофе","кофе черный","кофе чёрный","кофе черный без сахара"], category: "dessert", kcal: 2, protein: 0.1, fat: 0, carbs: 0 },
  { id: "kapuchino", name: "капучино", aliases: ["капуч"], category: "dessert", kcal: 45, protein: 2.5, fat: 2, carbs: 4.5 },
  { id: "latte", name: "латте", aliases: ["латте макиато"], category: "dessert", kcal: 55, protein: 3, fat: 2.5, carbs: 5 },
  { id: "kakao", name: "какао", aliases: ["какао напиток","горячее какао"], category: "dessert", kcal: 77, protein: 3.5, fat: 2.3, carbs: 10 },
  { id: "sok_apelsinovyy", name: "сок апельсиновый", aliases: ["апельсиновый сок"], category: "dessert", kcal: 45, protein: 0.7, fat: 0.2, carbs: 10.4 },
  { id: "sok_yablochnyy", name: "сок яблочный", aliases: ["яблочный сок"], category: "dessert", kcal: 46, protein: 0.1, fat: 0.1, carbs: 11.3 },
  { id: "kvas", name: "квас", aliases: ["квас хлебный"], category: "dessert", kcal: 27, protein: 0.2, fat: 0, carbs: 5.2 },
  { id: "kompot", name: "компот", aliases: ["компот фруктовый"], category: "dessert", kcal: 60, protein: 0.2, fat: 0, carbs: 15 },
  { id: "limonad", name: "лимонад", aliases: [], category: "dessert", kcal: 40, protein: 0, fat: 0, carbs: 10 },
  { id: "barley_dry", name: "перловка сухая", aliases: ["перловая крупа"], category: "side", kcal: 352, protein: 9.3, fat: 1.1, carbs: 73.7, source: "USDA" },
  { id: "millet_dry", name: "пшено сухое", aliases: ["пшенная крупа"], category: "side", kcal: 378, protein: 11, fat: 4.2, carbs: 73, source: "USDA" },
  { id: "bulgur_dry", name: "булгур сухой", aliases: ["булгур крупа"], category: "side", kcal: 342, protein: 12, fat: 1.3, carbs: 76, source: "USDA" },
  { id: "quinoa_dry", name: "киноа сухая", aliases: ["киноа крупа"], category: "side", kcal: 368, protein: 14.1, fat: 6.1, carbs: 64, source: "USDA" },
  { id: "couscous_dry", name: "кускус сухой", aliases: ["кускус"], category: "side", kcal: 376, protein: 12.8, fat: 0.6, carbs: 77.4, source: "USDA" },
  { id: "couscous_boiled", name: "кускус вареный", aliases: ["кускус отварной"], category: "side", kcal: 112, protein: 3.8, fat: 0.2, carbs: 23.2, source: "USDA" },
  { id: "oatmeal_water", name: "овсяная каша на воде", aliases: ["овсянка на воде","овсяная каша"], category: "side", kcal: 68, protein: 2.4, fat: 1.4, carbs: 12, source: "USDA" },
  { id: "oat_flakes_quick", name: "овсянка быстрого приготовления", aliases: ["овсянка моментальная"], category: "side", kcal: 366, protein: 11.9, fat: 7.2, carbs: 69, source: "manual_review" },
  { id: "rice_brown_boiled", name: "рис бурый вареный", aliases: ["бурый рис","коричневый рис"], category: "side", kcal: 111, protein: 2.6, fat: 0.9, carbs: 23, source: "USDA" },
  { id: "rice_brown_dry", name: "рис бурый сухой", aliases: ["бурый рис сухой"], category: "side", kcal: 370, protein: 7.9, fat: 2.9, carbs: 77.2, source: "USDA" },
  { id: "rice_basmati_boiled", name: "рис басмати вареный", aliases: ["басмати"], category: "side", kcal: 121, protein: 3.5, fat: 0.4, carbs: 25, source: "USDA" },
  { id: "rice_basmati_dry", name: "рис басмати сухой", aliases: ["басмати сухой"], category: "side", kcal: 365, protein: 7.5, fat: 0.7, carbs: 80, source: "USDA" },
  { id: "rice_round_dry", name: "рис круглозерный сухой", aliases: ["рис для каши"], category: "side", kcal: 365, protein: 7, fat: 0.7, carbs: 80, source: "USDA" },
  { id: "rice_round_boiled", name: "рис круглозерный вареный", aliases: ["круглый рис"], category: "side", kcal: 130, protein: 2.7, fat: 0.3, carbs: 28, source: "USDA" },
  { id: "rice_parboiled_dry", name: "рис пропаренный сухой", aliases: ["рис золотистый"], category: "side", kcal: 374, protein: 7.6, fat: 0.5, carbs: 82.5, source: "USDA" },
  { id: "rice_parboiled_boiled", name: "рис пропаренный вареный", aliases: ["пропаренный рис"], category: "side", kcal: 123, protein: 2.9, fat: 0.4, carbs: 26.5, source: "USDA" },
  { id: "rice_wild_boiled", name: "рис дикий вареный", aliases: ["дикий рис","черный рис вареный"], category: "side", kcal: 101, protein: 4, fat: 0.3, carbs: 21, source: "USDA" },
  { id: "rice_wild_dry", name: "рис дикий сухой", aliases: ["дикий рис сухой"], category: "side", kcal: 357, protein: 15, fat: 1.1, carbs: 75, source: "USDA" },
  { id: "rice_red_boiled", name: "рис красный вареный", aliases: ["красный рис"], category: "side", kcal: 111, protein: 2.6, fat: 0.9, carbs: 23, source: "manual_review" },
  { id: "rice_red_dry", name: "рис красный сухой", aliases: ["красный рис сухой"], category: "side", kcal: 370, protein: 7.9, fat: 2.9, carbs: 77, source: "manual_review" },
  { id: "buckwheat_green_dry", name: "гречка зеленая сухая", aliases: ["зеленая гречка"], category: "side", kcal: 306, protein: 12.6, fat: 2.6, carbs: 62, source: "USDA" },
  { id: "buckwheat_green_boiled", name: "гречка зеленая вареная", aliases: ["зеленая гречка вареная"], category: "side", kcal: 99, protein: 3.4, fat: 0.6, carbs: 19.9, source: "USDA" },
  { id: "barley_pearl_dry", name: "ячневая крупа сухая", aliases: ["ячменная крупа"], category: "side", kcal: 324, protein: 10, fat: 1.3, carbs: 66, source: "USDA" },
  { id: "barley_pearl_boiled", name: "ячневая крупа вареная", aliases: ["ячневая каша"], category: "side", kcal: 76, protein: 2.3, fat: 0.4, carbs: 16.7, source: "USDA" },
  { id: "corn_grits_dry", name: "кукурузная крупа сухая", aliases: ["кукурузная крупа"], category: "side", kcal: 337, protein: 7.6, fat: 1.2, carbs: 75, source: "USDA" },
  { id: "corn_grits_boiled", name: "кукурузная крупа вареная", aliases: ["кукурузная каша вареная"], category: "side", kcal: 86, protein: 2.3, fat: 0.3, carbs: 19, source: "USDA" },
  { id: "spelt_dry", name: "полба сухая", aliases: ["полба"], category: "side", kcal: 338, protein: 14.6, fat: 2.4, carbs: 70.4, source: "USDA" },
  { id: "spelt_boiled", name: "полба вареная", aliases: ["полба отварная"], category: "side", kcal: 124, protein: 5.3, fat: 0.8, carbs: 26.4, source: "USDA" },
  { id: "lentils_red_dry", name: "чечевица красная сухая", aliases: ["красная чечевица"], category: "side", kcal: 352, protein: 24, fat: 1.1, carbs: 63, source: "USDA" },
  { id: "lentils_green_dry", name: "чечевица зеленая сухая", aliases: ["зеленая чечевица"], category: "side", kcal: 352, protein: 24, fat: 1, carbs: 63, source: "USDA" },
  { id: "peas_split_dry", name: "горох колотый сухой", aliases: ["горох сухой"], category: "side", kcal: 352, protein: 24, fat: 1.2, carbs: 63, source: "USDA" },
  { id: "beans_white_dry", name: "фасоль белая сухая", aliases: ["фасоль сухая"], category: "side", kcal: 333, protein: 21, fat: 1.2, carbs: 61, source: "USDA" },
  { id: "amaranth_dry", name: "амарант сухой", aliases: ["амарант"], category: "side", kcal: 371, protein: 14, fat: 7, carbs: 65, source: "USDA" },
  { id: "amaranth_boiled", name: "амарант вареный", aliases: ["амарант отварной"], category: "side", kcal: 102, protein: 3.8, fat: 1.6, carbs: 19, source: "USDA" },
  { id: "rice_porridge_water", name: "рисовая каша на воде", aliases: ["рис каша"], category: "side", kcal: 78, protein: 1.5, fat: 0.2, carbs: 17.5, source: "manual_review" },
  { id: "semolina_dry", name: "манная крупа сухая", aliases: ["манка сухая"], category: "side", kcal: 360, protein: 11, fat: 1, carbs: 73, source: "USDA" },
  { id: "semolina_porridge_water", name: "манная каша на воде", aliases: ["манная каша"], category: "side", kcal: 80, protein: 2.5, fat: 0.2, carbs: 16.8, source: "manual_review" },
  { id: "millet_porridge_water", name: "пшенная каша на воде", aliases: ["пшено каша"], category: "side", kcal: 119, protein: 3.5, fat: 1, carbs: 23.7, source: "manual_review" },
  { id: "barley_porridge_water", name: "перловая каша на воде", aliases: ["перловка каша"], category: "side", kcal: 109, protein: 3.1, fat: 0.4, carbs: 22, source: "manual_review" },
  { id: "porridge_5_grains", name: "каша 5 злаков вареная", aliases: ["5 злаков"], category: "side", kcal: 105, protein: 3.5, fat: 1.2, carbs: 20.5, source: "manual_review" },
  { id: "flakes_5_grains_dry", name: "хлопья 5 злаков", aliases: ["смесь злаков"], category: "side", kcal: 355, protein: 11, fat: 3.5, carbs: 68, source: "manual_review" },
  { id: "corn_flakes_plain", name: "кукурузные хлопья", aliases: ["кукурузные хлопья без сахара"], category: "side", kcal: 357, protein: 7.5, fat: 1.2, carbs: 81, source: "USDA" },
  { id: "wheat_flakes", name: "пшеничные хлопья", aliases: ["пшёнка хлопья"], category: "side", kcal: 340, protein: 11, fat: 2, carbs: 68, source: "manual_review" },
  { id: "rice_flour", name: "рисовая мука", aliases: [], category: "side", kcal: 366, protein: 6, fat: 1.4, carbs: 80, source: "USDA" },
  { id: "oat_flour", name: "овсяная мука", aliases: [], category: "side", kcal: 389, protein: 13.2, fat: 6.5, carbs: 66, source: "USDA" },
  { id: "cornmeal_dry", name: "кукурузная мука", aliases: ["маисовая мука"], category: "side", kcal: 362, protein: 8.1, fat: 3.6, carbs: 77, source: "USDA" },
  { id: "polenta_dry", name: "полента сухая", aliases: ["кукурузная полента"], category: "side", kcal: 362, protein: 8.1, fat: 3.6, carbs: 77, source: "USDA" },
  { id: "polenta_boiled", name: "полента вареная", aliases: ["полента"], category: "side", kcal: 70, protein: 1.7, fat: 0.4, carbs: 15, source: "USDA" },
  { id: "sago_dry", name: "саго сухое", aliases: ["саго"], category: "side", kcal: 355, protein: 0.2, fat: 0, carbs: 88.7, source: "USDA" },
  { id: "sago_boiled", name: "саго вареное", aliases: ["саго отварное"], category: "side", kcal: 84, protein: 0.1, fat: 0, carbs: 21, source: "USDA" },
  { id: "teff_dry", name: "теф сухой", aliases: ["тефф"], category: "side", kcal: 367, protein: 13.3, fat: 2.4, carbs: 73, source: "USDA" },
  { id: "teff_boiled", name: "теф вареный", aliases: ["тефф вареный"], category: "side", kcal: 101, protein: 3.9, fat: 0.6, carbs: 20, source: "USDA" },
  { id: "sorghum_dry", name: "сорго сухое", aliases: ["сорго"], category: "side", kcal: 339, protein: 11.3, fat: 3.3, carbs: 75, source: "USDA" },
  { id: "sorghum_boiled", name: "сорго вареное", aliases: [], category: "side", kcal: 97, protein: 3.5, fat: 0.9, carbs: 21, source: "USDA" },
  { id: "spaghetti_dry", name: "спагетти сухие", aliases: ["спагетти"], category: "side", kcal: 371, protein: 13, fat: 1.5, carbs: 75, source: "USDA" },
  { id: "spaghetti_boiled", name: "спагетти вареные", aliases: ["спагетти отварные"], category: "side", kcal: 158, protein: 5.8, fat: 0.9, carbs: 31, source: "USDA" },
  { id: "vermicelli_dry", name: "вермишель сухая", aliases: ["вермишель"], category: "side", kcal: 371, protein: 13, fat: 1.5, carbs: 75, source: "USDA" },
  { id: "vermicelli_boiled", name: "вермишель вареная", aliases: ["вермишель отварная"], category: "side", kcal: 158, protein: 5.8, fat: 0.9, carbs: 31, source: "USDA" },
  { id: "penne_dry", name: "рожки сухие", aliases: ["рожки","пенне"], category: "side", kcal: 350, protein: 12, fat: 1.5, carbs: 72, source: "USDA" },
  { id: "penne_boiled", name: "рожки вареные", aliases: ["рожки отварные"], category: "side", kcal: 131, protein: 5, fat: 1.1, carbs: 25, source: "USDA" },
  { id: "fusilli_dry", name: "фузилли сухие", aliases: ["фузилли","спиральки"], category: "side", kcal: 350, protein: 12, fat: 1.5, carbs: 72, source: "USDA" },
  { id: "fusilli_boiled", name: "фузилли вареные", aliases: ["спиральки вареные"], category: "side", kcal: 131, protein: 5, fat: 1.1, carbs: 25, source: "USDA" },
  { id: "egg_noodles_dry", name: "лапша яичная сухая", aliases: ["яичная лапша"], category: "side", kcal: 384, protein: 14, fat: 4.5, carbs: 71, source: "USDA" },
  { id: "egg_noodles_boiled", name: "лапша яичная вареная", aliases: ["яичная лапша вареная"], category: "side", kcal: 138, protein: 4.5, fat: 2, carbs: 25, source: "USDA" },
  { id: "rice_noodles_dry", name: "лапша рисовая сухая", aliases: ["рисовая лапша"], category: "side", kcal: 364, protein: 5.8, fat: 0.6, carbs: 80, source: "USDA" },
  { id: "rice_noodles_boiled", name: "лапша рисовая вареная", aliases: ["рисовая лапша вареная"], category: "side", kcal: 109, protein: 1.8, fat: 0.2, carbs: 25, source: "USDA" },
  { id: "whole_wheat_pasta_dry", name: "макароны из твердых сортов сухие", aliases: ["макароны твердые сорта"], category: "side", kcal: 348, protein: 13, fat: 2, carbs: 68, source: "USDA" },
  { id: "whole_wheat_pasta_boiled", name: "макароны из твердых сортов вареные", aliases: ["макароны твердые сорта вареные"], category: "side", kcal: 124, protein: 5, fat: 0.8, carbs: 26, source: "USDA" },
  { id: "bread_borodinsky", name: "хлеб бородинский", aliases: ["бородинский хлеб"], category: "side", kcal: 210, protein: 6.8, fat: 1.3, carbs: 42, source: "manual_review" },
  { id: "toast_bread", name: "тостовый хлеб", aliases: ["тосты","хлеб для тостов"], category: "side", kcal: 280, protein: 9, fat: 4, carbs: 52, source: "USDA" },
  { id: "crispbread_rye", name: "хлебцы ржаные", aliases: ["хлебцы","хлебец","сухарики ржаные"], category: "side", kcal: 270, protein: 9, fat: 1.5, carbs: 58, source: "manual_review" },
  { id: "crispbread_wholegrain", name: "хлебцы цельнозерновые", aliases: ["цельнозерновые хлебцы","хлебцы цельнозерновые"], category: "side", kcal: 290, protein: 11, fat: 3, carbs: 52, source: "manual_review" },
  { id: "baguette", name: "багет", aliases: ["французский хлеб","багет французский"], category: "side", kcal: 274, protein: 9, fat: 1.5, carbs: 56, source: "USDA" },
  { id: "wheat_tortilla", name: "тортилья пшеничная", aliases: ["тортилья","лепешка тортилья","пшеничная тортилья"], category: "side", kcal: 304, protein: 8, fat: 7, carbs: 50, source: "USDA" },
  { id: "flatbread", name: "лепешка", aliases: ["лепешка пшеничная","лепёшка","лепёшка пшеничная"], category: "side", kcal: 275, protein: 8.5, fat: 2.5, carbs: 54, source: "manual_review" },
  { id: "bread_bran", name: "хлеб с отрубями", aliases: ["отрубной хлеб","хлеб отрубной"], category: "side", kcal: 230, protein: 8.5, fat: 2.5, carbs: 42, source: "manual_review" },
  { id: "bread_grain", name: "хлеб зерновой", aliases: ["зерновой хлеб"], category: "side", kcal: 250, protein: 9, fat: 3.5, carbs: 45, source: "manual_review" },
  { id: "bread_ciabatta", name: "чиабатта", aliases: ["хлеб чиабатта","чиабата","хлеб чиабата","ciabatta"], category: "side", kcal: 271, protein: 8.8, fat: 3.5, carbs: 52, source: "manual_review" },
  { id: "pita_bread", name: "пита", aliases: ["хлеб пита"], category: "side", kcal: 275, protein: 9, fat: 1.2, carbs: 56, source: "USDA" },
  { id: "croutons", name: "сухарики пшеничные", aliases: ["гренки"], category: "side", kcal: 350, protein: 11, fat: 4, carbs: 68, source: "manual_review" },
  { id: "breadcrumb", name: "панировочные сухари", aliases: ["панировка"], category: "side", kcal: 350, protein: 11, fat: 4, carbs: 68, source: "manual_review" },
  { id: "wheat_bran", name: "отруби пшеничные", aliases: ["отруби","отруби пшеничные"], category: "side", kcal: 216, protein: 16, fat: 4.5, carbs: 64, source: "USDA" },
  { id: "wheat_germ", name: "зародыши пшеницы", aliases: ["пшеничные зародыши"], category: "side", kcal: 360, protein: 23, fat: 10, carbs: 52, source: "USDA" },
  { id: "rice_paper", name: "рисовая бумага", aliases: ["рисовые листы"], category: "side", kcal: 349, protein: 3.5, fat: 0.3, carbs: 85, source: "manual_review" },
  { id: "noodles_buckwheat_dry", name: "гречневая лапша сухая", aliases: ["соба сухая"], category: "side", kcal: 348, protein: 14, fat: 1, carbs: 72, source: "manual_review" },
  { id: "noodles_buckwheat_boiled", name: "гречневая лапша вареная", aliases: ["соба","соба вареная"], category: "side", kcal: 99, protein: 5, fat: 0.1, carbs: 21, source: "manual_review" },
  { id: "couscous_whole_dry", name: "кускус цельнозерновой сухой", aliases: ["цельнозерновой кускус"], category: "side", kcal: 350, protein: 12, fat: 1.5, carbs: 72, source: "manual_review" },
  { id: "couscous_whole_boiled", name: "кускус цельнозерновой вареный", aliases: [], category: "side", kcal: 112, protein: 4, fat: 0.3, carbs: 23, source: "manual_review" },
  { id: "bulgur_porridge", name: "булгурная каша", aliases: ["каша из булгура"], category: "side", kcal: 83, protein: 3.1, fat: 0.2, carbs: 18.6, source: "manual_review" },
  { id: "quinoa_porridge", name: "киноа каша", aliases: ["каша из киноа"], category: "side", kcal: 120, protein: 4.4, fat: 1.9, carbs: 21.3, source: "manual_review" },
  { id: "millet_grits", name: "пшено шлифованное", aliases: ["шлифованное пшено"], category: "side", kcal: 378, protein: 11, fat: 4.2, carbs: 73, source: "manual_review" },
  { id: "barley_grits", name: "ячменная крупа", aliases: ["ячмень крупа"], category: "side", kcal: 324, protein: 10, fat: 1.3, carbs: 66, source: "manual_review" },
  { id: "pearl_barley_porridge", name: "ячневая каша", aliases: [], category: "side", kcal: 76, protein: 2.3, fat: 0.4, carbs: 16.7, source: "manual_review" },
  { id: "corn_porridge_milk_free", name: "кукурузная каша на воде", aliases: [], category: "side", kcal: 86, protein: 2.3, fat: 0.3, carbs: 19, source: "manual_review" },
  { id: "rice_cakes_plain", name: "рисовые хлебцы", aliases: ["рисовые лепешки"], category: "side", kcal: 387, protein: 8, fat: 3, carbs: 81, source: "USDA" },
  { id: "corn_tortilla", name: "тортилья кукурузная", aliases: ["кукурузная тортилья"], category: "side", kcal: 218, protein: 5.7, fat: 2.9, carbs: 44.6, source: "USDA" },
  { id: "bread_sliced_white", name: "хлеб нарезной белый", aliases: ["нарезной хлеб"], category: "side", kcal: 265, protein: 8, fat: 3.2, carbs: 49, source: "manual_review" },
  { id: "bread_sliced_rye", name: "хлеб нарезной ржаной", aliases: ["нарезной ржаной"], category: "side", kcal: 210, protein: 6.6, fat: 1.2, carbs: 43, source: "manual_review" },
  { id: "lavash_armenian", name: "лаваш армянский", aliases: ["армянский лаваш"], category: "side", kcal: 275, protein: 9.1, fat: 1.2, carbs: 56, source: "manual_review" },
  { id: "pasta_gluten_free_dry", name: "макароны без глютена сухие", aliases: ["безглютеновые макароны"], category: "side", kcal: 358, protein: 7, fat: 2, carbs: 79, source: "manual_review" },
  { id: "pasta_gluten_free_boiled", name: "макароны без глютена вареные", aliases: [], category: "side", kcal: 130, protein: 3, fat: 1, carbs: 28, source: "manual_review" },
  { id: "moloko_1", name: "молоко 1%", aliases: ["молоко обезжиренное"], category: "protein", kcal: 42, protein: 3.4, fat: 1, carbs: 4.8, source: "USDA" },
  { id: "moloko_2", name: "молоко 2%", aliases: [], category: "protein", kcal: 50, protein: 3.3, fat: 2, carbs: 4.8, source: "USDA" },
  { id: "moloko_3_8", name: "молоко 3.8%", aliases: ["молоко цельное"], category: "protein", kcal: 62, protein: 3.2, fat: 3.8, carbs: 4.8, source: "manual_review" },
  { id: "kefir_3_2", name: "кефир 3.2%", aliases: ["кефир 3,2%"], category: "protein", kcal: 59, protein: 3, fat: 3.2, carbs: 4, source: "manual_review" },
  { id: "prostokvasha", name: "простокваша", aliases: [], category: "protein", kcal: 53, protein: 2.8, fat: 3, carbs: 4.1, source: "manual_review" },
  { id: "varenets", name: "варенец", aliases: [], category: "protein", kcal: 67, protein: 2.8, fat: 4, carbs: 4.2, source: "manual_review" },
  { id: "ayran", name: "айран", aliases: [], category: "protein", kcal: 36, protein: 2.5, fat: 1.5, carbs: 3.5, source: "manual_review" },
  { id: "yogurt_greek", name: "греческий йогурт", aliases: ["йогурт греческий","греческий йогурт натуральный"], category: "protein", kcal: 97, protein: 9, fat: 5, carbs: 3.6, source: "USDA" },
  { id: "yogurt_0_fat", name: "йогурт обезжиренный", aliases: ["йогурт 0%","обезжиренный йогурт"], category: "protein", kcal: 56, protein: 5.7, fat: 0.2, carbs: 7.7, source: "USDA" },
  { id: "yogurt_fruit", name: "йогурт фруктовый", aliases: ["йогурт с фруктами"], category: "protein", kcal: 105, protein: 4, fat: 2.5, carbs: 17, source: "manual_review" },
  { id: "tvorog_0", name: "творог 0%", aliases: ["творог обезжиренный"], category: "protein", kcal: 71, protein: 16.5, fat: 0.6, carbs: 1.3, source: "USDA" },
  { id: "tvorog_2", name: "творог 2%", aliases: [], category: "protein", kcal: 103, protein: 17.5, fat: 2, carbs: 1.8, source: "manual_review" },
  { id: "tvorog_18", name: "творог 18%", aliases: [], category: "protein", kcal: 232, protein: 14, fat: 18, carbs: 2.8, source: "manual_review" },
  { id: "tvorog_zernistiy", name: "творог зернистый", aliases: ["зернистый творог"], category: "protein", kcal: 136, protein: 14, fat: 8, carbs: 2.5, source: "manual_review" },
  { id: "tvorozhok", name: "творожок", aliases: ["творожок детский"], category: "protein", kcal: 140, protein: 7.5, fat: 6, carbs: 14, source: "manual_review" },
  { id: "tvorozhnaya_massa", name: "творожная масса", aliases: [], category: "protein", kcal: 340, protein: 7, fat: 23, carbs: 28, source: "manual_review" },
  { id: "syrok_glazirovannyy", name: "сырок глазированный", aliases: ["глазированный сырок","сырок"], category: "protein", kcal: 350, protein: 8, fat: 20, carbs: 35, source: "manual_review" },
  { id: "slivki_33", name: "сливки 33%", aliases: ["сливки жирные"], category: "protein", kcal: 322, protein: 2.2, fat: 33, carbs: 3.7, source: "USDA" },
  { id: "smetana_15", name: "сметана 15%", aliases: ["сметана 15 процентов"], category: "protein", kcal: 158, protein: 2.6, fat: 15, carbs: 3.6, source: "manual_review" },
  { id: "smetana_25", name: "сметана 25%", aliases: [], category: "protein", kcal: 248, protein: 2.5, fat: 25, carbs: 3.2, source: "manual_review" },
  { id: "smetana_30", name: "сметана 30%", aliases: [], category: "protein", kcal: 293, protein: 2.4, fat: 30, carbs: 3.1, source: "manual_review" },
  { id: "syr_cheddar", name: "сыр чеддер", aliases: ["чеддер"], category: "protein", kcal: 403, protein: 25, fat: 33, carbs: 1.3, source: "USDA" },
  { id: "syr_parmesan", name: "сыр пармезан", aliases: ["пармезан"], category: "protein", kcal: 431, protein: 38, fat: 29, carbs: 4.1, source: "USDA" },
  { id: "syr_brie", name: "сыр бри", aliases: ["бри"], category: "protein", kcal: 334, protein: 21, fat: 28, carbs: 0.5, source: "USDA" },
  { id: "syr_camembert", name: "сыр камамбер", aliases: ["камамбер"], category: "protein", kcal: 300, protein: 20, fat: 24, carbs: 0.5, source: "USDA" },
  { id: "syr_suluguni", name: "сулугуни", aliases: ["сыр сулугуни"], category: "protein", kcal: 286, protein: 20, fat: 22, carbs: 0, source: "manual_review" },
  { id: "syr_adzhysky", name: "сыр адыгейский", aliases: ["адыгейский сыр"], category: "protein", kcal: 264, protein: 19.8, fat: 19.8, carbs: 1.5, source: "manual_review" },
  { id: "syr_ricotta", name: "сыр рикотта", aliases: ["рикотта"], category: "protein", kcal: 174, protein: 11, fat: 13, carbs: 3, source: "USDA" },
  { id: "syr_tilsiter", name: "сыр тилюзитер", aliases: ["тилюзитер"], category: "protein", kcal: 340, protein: 26, fat: 26, carbs: 0, source: "manual_review" },
  { id: "syr_emmental", name: "сыр эмменталь", aliases: ["эмменталь"], category: "protein", kcal: 380, protein: 29, fat: 28, carbs: 1.5, source: "USDA" },
  { id: "syr_holandskiy", name: "сыр голландский", aliases: ["голландский сыр"], category: "protein", kcal: 357, protein: 26, fat: 27, carbs: 2.2, source: "manual_review" },
  { id: "syr_brynza", name: "брынза", aliases: ["сыр брынза"], category: "protein", kcal: 260, protein: 22, fat: 19, carbs: 0.7, source: "manual_review" },
  { id: "syr_kostromskoy", name: "сыр костромской", aliases: [], category: "protein", kcal: 350, protein: 25, fat: 27, carbs: 0.5, source: "manual_review" },
  { id: "burrata", name: "буррата", aliases: [], category: "protein", kcal: 280, protein: 14, fat: 23, carbs: 2, source: "manual_review" },
  { id: "mascarpone", name: "маскарпоне", aliases: [], category: "protein", kcal: 429, protein: 4.6, fat: 44, carbs: 4.6, source: "USDA" },
  { id: "cream_cheese", name: "сливочный сыр", aliases: ["крем-сыр","крем сыр"], category: "protein", kcal: 342, protein: 6, fat: 34, carbs: 4, source: "USDA" },
  { id: "kurinaya_noga", name: "куриная ножка", aliases: ["куриные ножки","ножка курицы"], category: "protein", kcal: 214, protein: 26, fat: 12, carbs: 0, source: "USDA" },
  { id: "kurinoe_krylo", name: "куриное крыло", aliases: ["куриные крылья"], category: "protein", kcal: 203, protein: 18, fat: 14, carbs: 0, source: "USDA" },
  { id: "kuritsa_zharenaya", name: "курица жареная", aliases: ["жареная курица"], category: "protein", kcal: 220, protein: 25, fat: 12, carbs: 0, source: "manual_review" },
  { id: "kuritsa_kopchenaya", name: "курица копченая", aliases: [], category: "protein", kcal: 190, protein: 27, fat: 8, carbs: 0, source: "manual_review" },
  { id: "indeyka_grudka", name: "грудка индейки", aliases: ["индейка грудка","филе индейки"], category: "protein", kcal: 135, protein: 30, fat: 1, carbs: 0, source: "USDA" },
  { id: "utka", name: "утка", aliases: ["мясо утки"], category: "protein", kcal: 337, protein: 19, fat: 28, carbs: 0, source: "USDA" },
  { id: "gus", name: "гусь", aliases: ["мясо гуся"], category: "protein", kcal: 305, protein: 16, fat: 26, carbs: 0, source: "manual_review" },
  { id: "krolik", name: "кролик", aliases: ["мясо кролика"], category: "protein", kcal: 173, protein: 33, fat: 3.5, carbs: 0, source: "USDA" },
  { id: "govyazhya_vyrezka", name: "говяжья вырезка", aliases: ["вырезка говяжья","говяжий стейк"], category: "protein", kcal: 192, protein: 30, fat: 7, carbs: 0, source: "USDA" },
  { id: "steyk_govyazhiy", name: "стейк говяжий", aliases: ["стейк"], category: "protein", kcal: 271, protein: 26, fat: 18, carbs: 0, source: "manual_review" },
  { id: "svinaya_koreyka", name: "свиная корейка", aliases: ["корейка свиная"], category: "protein", kcal: 242, protein: 27, fat: 14, carbs: 0, source: "USDA" },
  { id: "svinaya_sheya", name: "свиная шея", aliases: [], category: "protein", kcal: 351, protein: 17, fat: 31, carbs: 0, source: "manual_review" },
  { id: "baranya_noga", name: "баранья нога", aliases: [], category: "protein", kcal: 234, protein: 25, fat: 14, carbs: 0, source: "manual_review" },
  { id: "farsh_svinoy", name: "фарш свиной", aliases: ["свиной фарш"], category: "protein", kcal: 263, protein: 17, fat: 21, carbs: 0, source: "USDA" },
  { id: "farsh_indeyki", name: "фарш индейки", aliases: ["индюшиный фарш"], category: "protein", kcal: 150, protein: 20, fat: 7, carbs: 0, source: "manual_review" },
  { id: "kolbasa_salyami", name: "салями", aliases: ["колбаса салями"], category: "protein", kcal: 425, protein: 21, fat: 37, carbs: 1, source: "USDA" },
  { id: "kolbasa_servelat", name: "сервелат", aliases: [], category: "protein", kcal: 360, protein: 14, fat: 32, carbs: 2, source: "manual_review" },
  { id: "rulet_kurinyy", name: "рулет куриный", aliases: ["куриный рулет"], category: "protein", kcal: 210, protein: 18, fat: 14, carbs: 2, source: "manual_review" },
  { id: "shashlyk_kurinyy", name: "шашлык куриный", aliases: ["шашлык из курицы"], category: "protein", kcal: 180, protein: 22, fat: 9, carbs: 1, source: "manual_review" },
  { id: "shashlyk_svinoy", name: "шашлык свиной", aliases: ["шашлык из свинины"], category: "protein", kcal: 260, protein: 20, fat: 19, carbs: 0, source: "manual_review" },
  { id: "losos_kopchenyy", name: "лосось копченый", aliases: ["семга копченая","копченый лосось"], category: "protein", kcal: 117, protein: 18, fat: 4.3, carbs: 0, source: "USDA" },
  { id: "forel_kopchenaya", name: "форель копченая", aliases: ["копченая форель"], category: "protein", kcal: 162, protein: 22, fat: 8, carbs: 0, source: "manual_review" },
  { id: "seld_solenaya", name: "сельдь соленая", aliases: ["селедка","селедка соленая"], category: "protein", kcal: 217, protein: 19, fat: 15, carbs: 0, source: "manual_review" },
  { id: "tunets_konservy", name: "тунец консервированный", aliases: ["тунец в масле","тунец консервы"], category: "protein", kcal: 198, protein: 26, fat: 8, carbs: 0, source: "USDA" },
  { id: "losos_konservy", name: "лосось консервированный", aliases: ["лосось консервы"], category: "protein", kcal: 180, protein: 22, fat: 9, carbs: 0, source: "manual_review" },
  { id: "karas", name: "карась", aliases: [], category: "protein", kcal: 127, protein: 17, fat: 6, carbs: 0, source: "manual_review" },
  { id: "schuka", name: "щука", aliases: [], category: "protein", kcal: 88, protein: 19, fat: 1, carbs: 0, source: "USDA" },
  { id: "okun", name: "окунь", aliases: ["окунь речной"], category: "protein", kcal: 91, protein: 19, fat: 1.2, carbs: 0, source: "manual_review" },
  { id: "som", name: "сом", aliases: [], category: "protein", kcal: 115, protein: 17, fat: 5, carbs: 0, source: "manual_review" },
  { id: "kambala", name: "камбала", aliases: [], category: "protein", kcal: 91, protein: 16, fat: 2.5, carbs: 0, source: "USDA" },
  { id: "paltus", name: "палтус", aliases: [], category: "protein", kcal: 91, protein: 18, fat: 1.3, carbs: 0, source: "USDA" },
  { id: "sudak", name: "судак", aliases: [], category: "protein", kcal: 84, protein: 18, fat: 1.1, carbs: 0, source: "manual_review" },
  { id: "sazan", name: "сазан", aliases: [], category: "protein", kcal: 97, protein: 18, fat: 2.7, carbs: 0, source: "manual_review" },
  { id: "dorada", name: "дорада", aliases: [], category: "protein", kcal: 96, protein: 19, fat: 2, carbs: 0, source: "manual_review" },
  { id: "seabass", name: "сибас", aliases: ["сибас рыба"], category: "protein", kcal: 97, protein: 18, fat: 2, carbs: 0, source: "manual_review" },
  { id: "ikra_chernaya", name: "икра черная", aliases: ["черная икра"], category: "protein", kcal: 252, protein: 24, fat: 18, carbs: 4, source: "manual_review" },
  { id: "krab", name: "краб", aliases: ["мясо краба"], category: "protein", kcal: 97, protein: 20, fat: 1.5, carbs: 0, source: "USDA" },
  { id: "osminog", name: "осьминог", aliases: [], category: "protein", kcal: 82, protein: 15, fat: 1, carbs: 2.2, source: "USDA" },
  { id: "grebek", name: "гребешок", aliases: ["морской гребешок"], category: "protein", kcal: 88, protein: 16, fat: 0.8, carbs: 3.2, source: "USDA" },
  { id: "ustritsy", name: "устрицы", aliases: ["устрица"], category: "protein", kcal: 68, protein: 7, fat: 2.5, carbs: 4, source: "USDA" },
  { id: "langustiny", name: "лангустины", aliases: ["лангустин"], category: "protein", kcal: 90, protein: 19, fat: 1, carbs: 0, source: "manual_review" },
  { id: "yaytso_varenoe", name: "яйцо вареное", aliases: ["вареное яйцо","яйца вареные"], category: "protein", kcal: 155, protein: 13, fat: 11, carbs: 1.1, source: "USDA" },
  { id: "perepelyinoe_yaytso", name: "перепелиное яйцо", aliases: ["яйцо перепелиное"], category: "protein", kcal: 158, protein: 13, fat: 11, carbs: 0.4, source: "USDA" },
  { id: "seitan", name: "сейтан", aliases: [], category: "protein", kcal: 120, protein: 22, fat: 2, carbs: 6, source: "manual_review" },
  { id: "tempeh", name: "темпе", aliases: ["темпе соевый"], category: "protein", kcal: 192, protein: 20, fat: 11, carbs: 7, source: "USDA" },
  { id: "tofu_kopchenyy", name: "тофу копченый", aliases: ["копченый тофу"], category: "protein", kcal: 120, protein: 15, fat: 5, carbs: 3, source: "manual_review" },
  { id: "protein_powder", name: "протеиновый порошок", aliases: ["протеин","сывороточный протеин"], category: "protein", kcal: 370, protein: 75, fat: 5, carbs: 8, source: "manual_review" },
  { id: "protein_bar", name: "протеиновый батончик", aliases: ["протеиновый бар"], category: "protein", kcal: 350, protein: 30, fat: 12, carbs: 30, source: "manual_review" },
  { id: "moloko_rastitelnoe_oat", name: "молоко овсяное", aliases: ["овсяное молоко"], category: "protein", kcal: 48, protein: 1, fat: 2.5, carbs: 6.5, source: "manual_review" },
  { id: "moloko_rastitelnoe_almond", name: "молоко миндальное", aliases: ["миндальное молоко"], category: "protein", kcal: 24, protein: 0.8, fat: 1.1, carbs: 3.4, source: "USDA" },
  { id: "yaytso_pashot", name: "яйцо пашот", aliases: ["пашот"], category: "protein", kcal: 143, protein: 13, fat: 10, carbs: 0.7, source: "manual_review" },
  { id: "yaytso_vsmyatku", name: "яйцо всмятку", aliases: ["яйца всмятку"], category: "protein", kcal: 155, protein: 13, fat: 11, carbs: 1.1, source: "manual_review" },
  { id: "yaytso_vkushenku", name: "яйцо вкрутую", aliases: ["яйца вкрутую"], category: "protein", kcal: 155, protein: 13, fat: 11, carbs: 1.1, source: "manual_review" },
  { id: "serdtse_kurinoe", name: "сердце куриное", aliases: ["куриные сердечки"], category: "protein", kcal: 185, protein: 16, fat: 13, carbs: 0.8, source: "manual_review" },
  { id: "yazyk_govyazhiy", name: "язык говяжий", aliases: ["говяжий язык"], category: "protein", kcal: 224, protein: 16, fat: 17, carbs: 0, source: "manual_review" },
  { id: "sheya_indeyki", name: "шея индейки", aliases: [], category: "protein", kcal: 144, protein: 19, fat: 7, carbs: 0, source: "manual_review" },
  { id: "file_kuritsy", name: "филе курицы", aliases: ["курица филе"], category: "protein", kcal: 165, protein: 31, fat: 3.6, carbs: 0, source: "manual_review" },
  { id: "salat_aysberg", name: "салат айсберг", aliases: ["айсберг","латук айсберг"], category: "vegetables", kcal: 14, protein: 0.9, fat: 0.1, carbs: 3, source: "USDA" },
  { id: "salat_romano", name: "салат романо", aliases: ["романо","ромэн","салат ромэн"], category: "vegetables", kcal: 17, protein: 1.2, fat: 0.3, carbs: 3.3, source: "USDA" },
  { id: "salat_latuk", name: "латук", aliases: ["салат латук"], category: "vegetables", kcal: 15, protein: 1.4, fat: 0.2, carbs: 2.9, source: "USDA" },
  { id: "salat_lollo_rosso", name: "салат лолло россо", aliases: ["лолло россо"], category: "vegetables", kcal: 15, protein: 1.4, fat: 0.2, carbs: 2.9, source: "manual_review" },
  { id: "salat_lollo_bionda", name: "салат лолло бионда", aliases: ["лолло бионда"], category: "vegetables", kcal: 15, protein: 1.4, fat: 0.2, carbs: 2.9, source: "manual_review" },
  { id: "rukkola", name: "руккола", aliases: ["рукола","арагула"], category: "vegetables", kcal: 25, protein: 2.6, fat: 0.7, carbs: 3.7, source: "USDA" },
  { id: "korn_salat", name: "салат корн", aliases: ["корн","корн-салат","маш"], category: "vegetables", kcal: 14, protein: 1.1, fat: 0.4, carbs: 2.3, source: "USDA" },
  { id: "frize", name: "салат фризе", aliases: ["фризе","фриссе"], category: "vegetables", kcal: 14, protein: 1.3, fat: 0.2, carbs: 2.8, source: "USDA" },
  { id: "radichio", name: "радичио", aliases: ["радиккио","цикорий радичио"], category: "vegetables", kcal: 23, protein: 1.4, fat: 0.3, carbs: 4.5, source: "USDA" },
  { id: "kinza", name: "кинза", aliases: ["кориандр зелень","кориандр"], category: "vegetables", kcal: 23, protein: 2.1, fat: 0.5, carbs: 3.7, source: "USDA" },
  { id: "bazilik", name: "базилик", aliases: ["базилик свежий"], category: "vegetables", kcal: 23, protein: 3.2, fat: 0.6, carbs: 2.7, source: "USDA" },
  { id: "myata", name: "мята", aliases: ["мята свежая"], category: "vegetables", kcal: 44, protein: 3.8, fat: 0.9, carbs: 8.4, source: "USDA" },
  { id: "zelenyy_luk", name: "зеленый лук", aliases: ["зеленый лук перо","лук зеленый"], category: "vegetables", kcal: 32, protein: 1.8, fat: 0.2, carbs: 7.3, source: "USDA" },
  { id: "shnitt_luk", name: "шнитт-лук", aliases: ["шнитт лук","лук шнитт"], category: "vegetables", kcal: 30, protein: 3.3, fat: 0.7, carbs: 4.4, source: "USDA" },
  { id: "timyan", name: "тимьян", aliases: ["тимьян свежий","чабрец"], category: "vegetables", kcal: 31, protein: 1.7, fat: 0.5, carbs: 6.8, source: "manual_review" },
  { id: "rozmarin", name: "розмарин", aliases: ["розмарин свежий"], category: "vegetables", kcal: 131, protein: 3.3, fat: 5.9, carbs: 20.7, source: "USDA" },
  { id: "oregano", name: "орегано", aliases: ["душица","орегано свежий"], category: "vegetables", kcal: 25, protein: 1.7, fat: 0.4, carbs: 4.1, source: "manual_review" },
  { id: "kapusta_krasnokochannaya", name: "капуста краснокочанная", aliases: ["краснокочанная капуста","капуста красная"], category: "vegetables", kcal: 31, protein: 1.4, fat: 0.2, carbs: 7.4, source: "USDA" },
  { id: "kapusta_pekinskaya", name: "капуста пекинская", aliases: ["пекинская капуста","ча капуста"], category: "vegetables", kcal: 16, protein: 1.2, fat: 0.2, carbs: 3.2, source: "USDA" },
  { id: "kapusta_bryusselskaya", name: "капуста брюссельская", aliases: ["брюссельская капуста","брюссельская"], category: "vegetables", kcal: 43, protein: 3.4, fat: 0.3, carbs: 9, source: "USDA" },
  { id: "kapusta_savoyskaya", name: "капуста савойская", aliases: ["савойская капуста"], category: "vegetables", kcal: 27, protein: 2, fat: 0.1, carbs: 6.1, source: "USDA" },
  { id: "kohlrabi", name: "кольраби", aliases: ["капуста кольраби"], category: "vegetables", kcal: 27, protein: 1.7, fat: 0.1, carbs: 6.2, source: "USDA" },
  { id: "griby_shampinony", name: "шампиньоны", aliases: ["шампиньон","грибы шампиньоны"], category: "vegetables", kcal: 22, protein: 3.1, fat: 0.3, carbs: 3.3, source: "USDA" },
  { id: "griby_veshenki", name: "вешенки", aliases: ["грибы вешенки","вешенка"], category: "vegetables", kcal: 33, protein: 3.3, fat: 0.4, carbs: 6.1, source: "USDA" },
  { id: "griby_belye", name: "грибы белые", aliases: ["белый гриб","боровики"], category: "vegetables", kcal: 26, protein: 3.7, fat: 0.7, carbs: 4.1, source: "manual_review" },
  { id: "griby_lisichki", name: "лисички", aliases: ["грибы лисички","лисичка"], category: "vegetables", kcal: 32, protein: 1.5, fat: 0.5, carbs: 6.9, source: "manual_review" },
  { id: "griby_opyata", name: "опята", aliases: ["грибы опята","опенок"], category: "vegetables", kcal: 22, protein: 2.2, fat: 0.5, carbs: 3.9, source: "manual_review" },
  { id: "griby_shiitake", name: "шиитаке", aliases: ["грибы шиитаке","шитаке"], category: "vegetables", kcal: 34, protein: 2.2, fat: 0.5, carbs: 6.8, source: "USDA" },
  { id: "cukini", name: "цукини", aliases: ["кабачок цукини","цуккини"], category: "vegetables", kcal: 17, protein: 1.2, fat: 0.3, carbs: 3.1, source: "USDA" },
  { id: "perets_krasnyy", name: "перец красный", aliases: ["красный перец","перец болгарский красный"], category: "vegetables", kcal: 31, protein: 1, fat: 0.3, carbs: 6, source: "USDA" },
  { id: "perets_zheltyy", name: "перец желтый", aliases: ["желтый перец","перец болгарский желтый"], category: "vegetables", kcal: 27, protein: 1, fat: 0.2, carbs: 6.3, source: "USDA" },
  { id: "perets_zelenyy", name: "перец зеленый", aliases: ["зеленый перец","перец болгарский зеленый"], category: "vegetables", kcal: 20, protein: 0.9, fat: 0.2, carbs: 4.6, source: "USDA" },
  { id: "redka", name: "редька", aliases: ["редька черная","черная редька"], category: "vegetables", kcal: 35, protein: 1.6, fat: 0.2, carbs: 7.9, source: "manual_review" },
  { id: "daykon", name: "дайкон", aliases: ["редька дайкон","дайкон редька"], category: "vegetables", kcal: 18, protein: 0.6, fat: 0.1, carbs: 4.1, source: "USDA" },
  { id: "repa", name: "репа", aliases: ["репа белая"], category: "vegetables", kcal: 28, protein: 0.9, fat: 0.1, carbs: 6.4, source: "USDA" },
  { id: "pasternak", name: "пастернак", aliases: ["пастернак корень"], category: "vegetables", kcal: 75, protein: 1.2, fat: 0.3, carbs: 18, source: "USDA" },
  { id: "selderey_steblevoy", name: "сельдерей стеблевой", aliases: ["сельдерей","сельдерей стебли"], category: "vegetables", kcal: 14, protein: 0.7, fat: 0.2, carbs: 3, source: "USDA" },
  { id: "selderey_kornevoy", name: "сельдерей корневой", aliases: ["сельдерей корень","корневой сельдерей"], category: "vegetables", kcal: 42, protein: 1.5, fat: 0.3, carbs: 9.2, source: "USDA" },
  { id: "sparzha", name: "спаржа", aliases: ["спаржа свежая"], category: "vegetables", kcal: 20, protein: 2.2, fat: 0.1, carbs: 3.9, source: "USDA" },
  { id: "artishok", name: "артишок", aliases: ["артишоки"], category: "vegetables", kcal: 47, protein: 3.3, fat: 0.2, carbs: 11, source: "USDA" },
  { id: "goroh_saharnyy", name: "горошек сахарный", aliases: ["сахарный горошек","горошек сахарный"], category: "vegetables", kcal: 42, protein: 2.8, fat: 0.2, carbs: 7.5, source: "USDA" },
  { id: "ovoschnaya_smes_zam", name: "овощная смесь замороженная", aliases: ["овощная смесь","замороженные овощи"], category: "vegetables", kcal: 35, protein: 2, fat: 0.3, carbs: 7, source: "manual_review" },
  { id: "meksikanskaya_smes_zam", name: "мексиканская смесь замороженная", aliases: ["мексиканская смесь","мексиканские овощи"], category: "vegetables", kcal: 40, protein: 2.5, fat: 0.4, carbs: 8, source: "manual_review" },
  { id: "vesennyaya_smes_zam", name: "весенняя смесь замороженная", aliases: ["весенняя смесь","весенние овощи"], category: "vegetables", kcal: 25, protein: 2, fat: 0.2, carbs: 4.5, source: "manual_review" },
  { id: "luk_porey", name: "лук-порей", aliases: ["порей","лук порей"], category: "vegetables", kcal: 61, protein: 1.5, fat: 0.3, carbs: 14.2, source: "USDA" },
  { id: "batat", name: "батат", aliases: ["сладкий картофель"], category: "vegetables", kcal: 86, protein: 1.6, fat: 0.1, carbs: 20.1, source: "USDA" },
  { id: "kukuruza_svezhaya", name: "кукуруза свежая", aliases: ["кукуруза початок","кукуруза в початках"], category: "vegetables", kcal: 96, protein: 3.4, fat: 1.5, carbs: 21, source: "USDA" },
  { id: "avokado", name: "авокадо", aliases: ["авокадо свежее"], category: "vegetables", kcal: 160, protein: 2, fat: 15, carbs: 8.5, source: "USDA" },
  { id: "imbir", name: "имбирь", aliases: ["имбирь корень","имбирь свежий"], category: "vegetables", kcal: 80, protein: 1.8, fat: 0.8, carbs: 17.8, source: "USDA" },
  { id: "perets_chili", name: "перец чили", aliases: ["чили","перец острый","острый перец"], category: "vegetables", kcal: 40, protein: 1.9, fat: 0.4, carbs: 8.8, source: "USDA" },
  { id: "pomidor_cherri", name: "помидоры черри", aliases: ["черри","томаты черри"], category: "vegetables", kcal: 18, protein: 0.9, fat: 0.2, carbs: 3.9, source: "USDA" },
  { id: "kapusta_bok_choy", name: "пак-чой", aliases: ["бок чой","капуста пак-чой"], category: "vegetables", kcal: 13, protein: 1.5, fat: 0.2, carbs: 2.2, source: "USDA" },
  { id: "kale", name: "кейл", aliases: ["кале","капуста кейл"], category: "vegetables", kcal: 35, protein: 2.9, fat: 0.4, carbs: 4.4, source: "USDA" },
  { id: "kress_salat", name: "кресс-салат", aliases: ["кресс салат","водяной кресс"], category: "vegetables", kcal: 11, protein: 2.3, fat: 0.1, carbs: 1.3, source: "USDA" },
  { id: "salat_mash", name: "салат микс", aliases: ["микс салатов","салатный микс"], category: "vegetables", kcal: 18, protein: 1.5, fat: 0.2, carbs: 3, source: "manual_review" },
  { id: "topinambur", name: "топинамбур", aliases: ["земляная груша"], category: "vegetables", kcal: 73, protein: 2, fat: 0, carbs: 17.4, source: "manual_review" },
  { id: "patisson", name: "патиссон", aliases: ["патиссоны"], category: "vegetables", kcal: 19, protein: 1.2, fat: 0.2, carbs: 3.3, source: "manual_review" },
  { id: "kabachki_molodye", name: "кабачки молодые", aliases: ["молодые кабачки"], category: "vegetables", kcal: 16, protein: 1.2, fat: 0.2, carbs: 3, source: "manual_review" },
  { id: "shalfej", name: "шалфей", aliases: ["шалфей свежий"], category: "vegetables", kcal: 26, protein: 1.5, fat: 0.6, carbs: 3.9, source: "manual_review" },
  { id: "estragon", name: "эстрагон", aliases: ["тархун"], category: "vegetables", kcal: 24, protein: 1.9, fat: 0.3, carbs: 5, source: "manual_review" },
  { id: "griby_lesnye_smes", name: "грибы лесные смесь", aliases: ["грибы смесь","лесные грибы"], category: "vegetables", kcal: 28, protein: 2.5, fat: 0.5, carbs: 4.5, source: "manual_review" },
  { id: "brokkoli_zam", name: "брокколи замороженная", aliases: ["брокколи замороженная"], category: "vegetables", kcal: 34, protein: 2.8, fat: 0.4, carbs: 6.6, source: "USDA" },
  { id: "shpinat_zam", name: "шпинат замороженный", aliases: ["шпинат замороженный"], category: "vegetables", kcal: 23, protein: 2.9, fat: 0.4, carbs: 3.6, source: "USDA" },
  { id: "goroh_zam", name: "горошек замороженный", aliases: ["горошек замороженный"], category: "vegetables", kcal: 81, protein: 5.4, fat: 0.4, carbs: 14.5, source: "USDA" },
  { id: "fasol_zam", name: "фасоль стручковая замороженная", aliases: ["стручковая фасоль замороженная"], category: "vegetables", kcal: 31, protein: 1.8, fat: 0.1, carbs: 7, source: "USDA" },
  { id: "ogurets_marinovannyy", name: "огурец маринованный", aliases: ["огурцы маринованные","корнишоны"], category: "vegetables", kcal: 11, protein: 0.4, fat: 0.1, carbs: 2.3, source: "manual_review" },
  { id: "tomaty_sushenye", name: "томаты сушеные", aliases: ["вяленые томаты","томаты вяленые"], category: "vegetables", kcal: 258, protein: 14.1, fat: 3, carbs: 55.8, source: "USDA" },
  { id: "salat_kapusta_morkov", name: "салат капуста с морковью", aliases: ["капуста с морковью"], category: "vegetables", kcal: 45, protein: 1.5, fat: 2, carbs: 6, source: "manual_review" },
  { id: "laym", name: "лайм", aliases: ["лаймы"], category: "dessert", kcal: 30, protein: 0.7, fat: 0.2, carbs: 10.5, source: "USDA" },
  { id: "greypfrut", name: "грейпфрут", aliases: ["грейпфруты"], category: "dessert", kcal: 42, protein: 0.8, fat: 0.1, carbs: 10.7, source: "USDA" },
  { id: "pomelo", name: "помело", aliases: ["помелло"], category: "dessert", kcal: 38, protein: 0.8, fat: 0.1, carbs: 9.6, source: "manual_review" },
  { id: "inzhir_svezhiy", name: "инжир", aliases: ["инжир свежий","инжир свежий фрукт"], category: "dessert", kcal: 74, protein: 0.8, fat: 0.3, carbs: 19.2, source: "USDA" },
  { id: "ayva", name: "айва", aliases: ["айвы"], category: "dessert", kcal: 57, protein: 0.4, fat: 0.1, carbs: 15.3, source: "USDA" },
  { id: "papaya", name: "папайя", aliases: ["папайя фрукт","папаия"], category: "dessert", kcal: 43, protein: 0.5, fat: 0.3, carbs: 11, source: "USDA" },
  { id: "marakuyya", name: "маракуйя", aliases: ["маракуйя фрукт","пассифлора"], category: "dessert", kcal: 97, protein: 2.2, fat: 0.7, carbs: 23.4, source: "USDA" },
  { id: "zemlyanika", name: "земляника", aliases: ["земляника лесная"], category: "dessert", kcal: 33, protein: 0.7, fat: 0.3, carbs: 7.5, source: "manual_review" },
  { id: "ezhevika", name: "ежевика", aliases: ["ежевика свежая"], category: "dessert", kcal: 43, protein: 1.4, fat: 0.5, carbs: 9.6, source: "USDA" },
  { id: "golubika", name: "голубика", aliases: ["голубика свежая","черника американская"], category: "dessert", kcal: 57, protein: 0.7, fat: 0.3, carbs: 14.5, source: "USDA" },
  { id: "brusnika", name: "брусника", aliases: ["брусника свежая"], category: "dessert", kcal: 54, protein: 0.7, fat: 0.5, carbs: 12.2, source: "manual_review" },
  { id: "smorodina_chernaya", name: "смородина черная", aliases: ["черная смородина","чёрная смородина","смородина чёрная"], category: "dessert", kcal: 63, protein: 1.4, fat: 0.4, carbs: 15.4, source: "USDA" },
  { id: "smorodina_krasnaya", name: "смородина красная", aliases: ["красная смородина","смородина красная"], category: "dessert", kcal: 56, protein: 1.4, fat: 0.2, carbs: 13.8, source: "USDA" },
  { id: "kryzhovnik", name: "крыжовник", aliases: ["крыжовник свежий"], category: "dessert", kcal: 44, protein: 0.9, fat: 0.6, carbs: 10.2, source: "USDA" },
  { id: "oblepikha", name: "облепиха", aliases: ["облепиха свежая"], category: "dessert", kcal: 82, protein: 1.2, fat: 5.4, carbs: 7, source: "manual_review" },
  { id: "yabloki_sushenye", name: "яблоки сушеные", aliases: ["яблоко сушеное","сушеные яблоки","сушёные яблоки"], category: "dessert", kcal: 243, protein: 0.9, fat: 0.3, carbs: 65.9, source: "USDA" },
  { id: "mango_sushenoe", name: "манго сушеное", aliases: ["сушеное манго","манго сушёное"], category: "dessert", kcal: 319, protein: 2.5, fat: 1.2, carbs: 78.6, source: "USDA" },
  { id: "banan_sushyenyy", name: "банан сушеный", aliases: ["банан сушёный","сушеный банан","банановые чипсы"], category: "dessert", kcal: 346, protein: 3.9, fat: 1.8, carbs: 88.3, source: "USDA" },
  { id: "kedrovye_orehi", name: "кедровые орехи", aliases: ["кедровый орех","орех кедровый","сосновые орехи"], category: "dessert", kcal: 673, protein: 13.7, fat: 68.4, carbs: 13.1, source: "USDA" },
  { id: "brazilskiy_oreh", name: "бразильский орех", aliases: ["бразильские орехи","орех бразильский"], category: "dessert", kcal: 659, protein: 14.3, fat: 67.1, carbs: 11.7, source: "USDA" },
  { id: "kunzhut", name: "кунжут", aliases: ["семена кунжута","сезам","кунжут семена"], category: "dessert", kcal: 573, protein: 17.7, fat: 49.7, carbs: 23.4, source: "USDA" },
  { id: "kokos", name: "кокос", aliases: ["кокос свежий","кокосовая мякоть"], category: "dessert", kcal: 354, protein: 3.3, fat: 33.5, carbs: 15.2, source: "USDA" },
  { id: "limonnik", name: "лимонник", aliases: ["ягода лимонника","лимонник ягода"], category: "dessert", kcal: 45, protein: 2, fat: 0.5, carbs: 8, source: "manual_review" },
  { id: "shipovnik", name: "шиповник", aliases: ["шиповник плоды","плоды шиповника"], category: "dessert", kcal: 162, protein: 1.6, fat: 0.3, carbs: 38.2, source: "manual_review" },
  { id: "zhimolost", name: "жимолость", aliases: ["жимолость ягода","жимолость съедобная"], category: "dessert", kcal: 36, protein: 0.8, fat: 0.5, carbs: 8.2, source: "manual_review" },
  { id: "yagody_zamorozhennye", name: "ягоды замороженные", aliases: ["замороженные ягоды","смесь ягод замороженная"], category: "dessert", kcal: 45, protein: 0.8, fat: 0.3, carbs: 10.5, source: "manual_review" },
  { id: "frukty_sushenye_smes", name: "сухофрукты смесь", aliases: ["смесь сухофруктов","ассорти сухофруктов"], category: "dessert", kcal: 280, protein: 3, fat: 1, carbs: 68, source: "manual_review" },
  { id: "orehi_smes", name: "орехи смесь", aliases: ["смесь орехов","ассорти орехов"], category: "dessert", kcal: 600, protein: 18, fat: 55, carbs: 18, source: "manual_review" },
  { id: "greypfrut_krasnyy", name: "грейпфрут красный", aliases: ["красный грейпфрут"], category: "dessert", kcal: 42, protein: 0.8, fat: 0.1, carbs: 10.7, source: "USDA" },
  { id: "vinograd_zelenyy", name: "виноград зеленый", aliases: ["зеленый виноград","виноград белый"], category: "dessert", kcal: 69, protein: 0.7, fat: 0.2, carbs: 18, source: "manual_review" },
  { id: "vinograd_krasnyy", name: "виноград красный", aliases: ["красный виноград","виноград темный"], category: "dessert", kcal: 69, protein: 0.7, fat: 0.2, carbs: 18, source: "manual_review" },
  { id: "voda_pitievaya", name: "вода питьевая", aliases: ["вода","питьевая вода"], category: "dessert", kcal: 0, protein: 0, fat: 0, carbs: 0, source: "USDA" },
  { id: "voda_mineralnaya", name: "минеральная вода", aliases: ["вода минеральная"], category: "dessert", kcal: 0, protein: 0, fat: 0, carbs: 0, source: "USDA" },
  { id: "voda_gazirovannaya", name: "вода газированная", aliases: ["газированная вода","газировка без сахара"], category: "dessert", kcal: 0, protein: 0, fat: 0, carbs: 0, source: "USDA" },
  { id: "espresso", name: "эспрессо", aliases: ["еспрессо"], category: "dessert", kcal: 9, protein: 0.1, fat: 0.2, carbs: 1.7, source: "USDA" },
  { id: "americano", name: "американо", aliases: ["америк","кофе американо"], category: "dessert", kcal: 2, protein: 0.1, fat: 0, carbs: 0, source: "manual_review" },
  { id: "raf", name: "раф", aliases: ["раф кофе","кофе раф"], category: "dessert", kcal: 220, protein: 3, fat: 14, carbs: 20, source: "manual_review" },
  { id: "chay_zelenyy", name: "чай зеленый", aliases: ["зелёный чай","чай зелёный","зеленый чай"], category: "dessert", kcal: 1, protein: 0, fat: 0, carbs: 0, source: "USDA" },
  { id: "chay_travyanoy", name: "чай травяной", aliases: ["травяной чай","чай травяной"], category: "dessert", kcal: 1, protein: 0, fat: 0, carbs: 0, source: "manual_review" },
  { id: "chay_chernyy", name: "чай черный", aliases: ["чай чёрный","чёрный чай"], category: "dessert", kcal: 1, protein: 0, fat: 0, carbs: 0, source: "USDA" },
  { id: "tsikoriy", name: "цикорий", aliases: ["напиток цикорий","цикорий напиток"], category: "dessert", kcal: 21, protein: 0.2, fat: 0, carbs: 4.5, source: "manual_review" },
  { id: "sok_tomatnyy", name: "сок томатный", aliases: ["томатный сок"], category: "dessert", kcal: 17, protein: 0.8, fat: 0.1, carbs: 3.5, source: "USDA" },
  { id: "sok_vinogradnyy", name: "сок виноградный", aliases: ["виноградный сок"], category: "dessert", kcal: 60, protein: 0.3, fat: 0.1, carbs: 14.8, source: "USDA" },
  { id: "mors_klyukvennyy", name: "морс клюквенный", aliases: ["клюквенный морс","морс из клюквы"], category: "dessert", kcal: 40, protein: 0.1, fat: 0, carbs: 10, source: "manual_review" },
  { id: "mors_yagodnyy", name: "морс ягодный", aliases: ["ягодный морс","морс из ягод"], category: "dessert", kcal: 45, protein: 0.2, fat: 0, carbs: 11, source: "manual_review" },
  { id: "kompot_suhofrukty", name: "компот из сухофруктов", aliases: ["компот сухофрукты","компот из сухофруктов"], category: "dessert", kcal: 70, protein: 0.3, fat: 0, carbs: 17, source: "manual_review" },
  { id: "shokolad_gorkiy", name: "шоколад горький", aliases: ["горький шоколад","шоколад 70%","шоколад 85%"], category: "dessert", kcal: 598, protein: 7.8, fat: 42.6, carbs: 45.9, source: "USDA" },
  { id: "konfety_shokoladnye", name: "конфеты шоколадные", aliases: ["шоколадные конфеты","конфеты"], category: "dessert", kcal: 450, protein: 4, fat: 20, carbs: 65, source: "manual_review" },
  { id: "karamel", name: "карамель", aliases: ["карамельки","конфеты карамель"], category: "dessert", kcal: 382, protein: 4.6, fat: 8.1, carbs: 77, source: "USDA" },
  { id: "iris", name: "ирис", aliases: ["конфеты ирис","ирисок"], category: "dessert", kcal: 387, protein: 2.6, fat: 8, carbs: 78, source: "manual_review" },
  { id: "pastila", name: "пастила", aliases: ["пастилки"], category: "dessert", kcal: 310, protein: 0.5, fat: 0, carbs: 80, source: "manual_review" },
  { id: "djem", name: "джем", aliases: ["варенье джем"], category: "dessert", kcal: 250, protein: 0.4, fat: 0.1, carbs: 65, source: "USDA" },
  { id: "pechene_ovsyane", name: "печенье овсяное", aliases: ["овсяное печенье","печенье овсянное"], category: "dessert", kcal: 430, protein: 6.5, fat: 16, carbs: 65, source: "manual_review" },
  { id: "kreker", name: "крекер", aliases: ["крекеры","сухое печенье"], category: "dessert", kcal: 400, protein: 10, fat: 10, carbs: 70, source: "manual_review" },
  { id: "pryaniki", name: "пряники", aliases: ["пряник","пряник медовый"], category: "dessert", kcal: 350, protein: 5, fat: 3, carbs: 75, source: "manual_review" },
  { id: "ponchik", name: "пончик", aliases: ["пончики","донат"], category: "dessert", kcal: 421, protein: 5, fat: 23, carbs: 48, source: "USDA" },
  { id: "morozhenoe_slivochnoe", name: "мороженое сливочное", aliases: ["мороженое ванильное","сливочное мороженое"], category: "dessert", kcal: 207, protein: 3.5, fat: 11, carbs: 24, source: "USDA" },
  { id: "fruktovyy_led", name: "фруктовый лед", aliases: ["эскимо фруктовое","лед фруктовый","сорбет"], category: "dessert", kcal: 120, protein: 0.5, fat: 0.2, carbs: 30, source: "manual_review" },
  { id: "mayonez_legkiy", name: "майонез лёгкий", aliases: ["лёгкий майонез","легкий майонез","майонез легкий"], category: "dessert", kcal: 300, protein: 1, fat: 30, carbs: 4, source: "manual_review" },
  { id: "sous_teriyaki", name: "соус терияки", aliases: ["терияки","соус терияки"], category: "dessert", kcal: 89, protein: 3.8, fat: 0.1, carbs: 19.2, source: "USDA" },
  { id: "sous_barbekyu", name: "соус барбекю", aliases: ["барбекю","соус bbq","bbq соус"], category: "dessert", kcal: 170, protein: 1.5, fat: 0.5, carbs: 41, source: "USDA" },
  { id: "sous_tartar", name: "соус тартар", aliases: ["тартар","соус тар-тар"], category: "dessert", kcal: 220, protein: 1.5, fat: 20, carbs: 8, source: "manual_review" },
  { id: "sous_chesnochnyy", name: "чесночный соус", aliases: ["чесночный","соус чесночный"], category: "dessert", kcal: 400, protein: 2, fat: 38, carbs: 12, source: "manual_review" },
  { id: "sous_syrnyy", name: "сырный соус", aliases: ["соус сырный","сырный"], category: "dessert", kcal: 250, protein: 5, fat: 20, carbs: 10, source: "manual_review" },
  { id: "sous_pesto", name: "соус песто", aliases: ["песто","песто соус"], category: "dessert", kcal: 454, protein: 5, fat: 45, carbs: 5, source: "USDA" },
  { id: "adjika", name: "аджика", aliases: ["аджика острая"], category: "dessert", kcal: 60, protein: 2, fat: 3, carbs: 6, source: "manual_review" },
  { id: "hren_stolovyj", name: "хрен столовый", aliases: ["хрен","хрен готовый"], category: "dessert", kcal: 48, protein: 3.2, fat: 0.4, carbs: 10.3, source: "manual_review" },
  { id: "uksus_balsamicheskiy", name: "бальзамический уксус", aliases: ["бальзамик","уксус бальзамический"], category: "dessert", kcal: 88, protein: 0.5, fat: 0, carbs: 17, source: "USDA" },
  { id: "uksus_yablochnyy", name: "яблочный уксус", aliases: ["уксус яблочный"], category: "dessert", kcal: 21, protein: 0, fat: 0, carbs: 0.9, source: "USDA" },
  { id: "uksus_vinnyy", name: "винный уксус", aliases: ["уксус винный","уксус виноградный"], category: "dessert", kcal: 19, protein: 0, fat: 0, carbs: 0.4, source: "USDA" },
  { id: "limonnyy_sok", name: "лимонный сок", aliases: ["сок лимонный","лимон сок"], category: "dessert", kcal: 22, protein: 0.4, fat: 0.2, carbs: 6.9, source: "USDA" },
  { id: "salatnaya_zapravka", name: "салатная заправка", aliases: ["заправка для салата","заправка салатная"], category: "dessert", kcal: 250, protein: 0.5, fat: 22, carbs: 12, source: "manual_review" },
  { id: "yogurtovaya_zapravka", name: "йогуртовая заправка", aliases: ["заправка йогуртовая"], category: "dessert", kcal: 150, protein: 2, fat: 12, carbs: 8, source: "manual_review" },
  { id: "sahar_trostnikovyy", name: "сахар тростниковый", aliases: ["тростниковый сахар","сахар коричневый"], category: "dessert", kcal: 387, protein: 0, fat: 0, carbs: 100, source: "USDA" },
  { id: "saharnaya_pudra", name: "сахарная пудра", aliases: ["пудра","сахар пудра"], category: "dessert", kcal: 389, protein: 0, fat: 0, carbs: 99.8, source: "USDA" },
  { id: "saharozamenitel", name: "сахарозаменитель", aliases: ["заменитель сахара","подсластитель"], category: "dessert", kcal: 4, protein: 0, fat: 0, carbs: 1, source: "manual_review" },
  { id: "stevia", name: "стевия", aliases: ["стевия подсластитель","экстракт стевии"], category: "dessert", kcal: 0, protein: 0, fat: 0, carbs: 0, source: "manual_review" },
  { id: "kakao_poroshok", name: "какао-порошок", aliases: ["какао порошок","какао","порошок какао"], category: "dessert", kcal: 228, protein: 19.6, fat: 13.7, carbs: 57.9, source: "USDA" },
  { id: "kletchatka", name: "клетчатка", aliases: ["пищевая клетчатка","волокна пищевые"], category: "dessert", kcal: 200, protein: 0, fat: 0, carbs: 80, source: "manual_review" },
  { id: "otruby_ovsyanie", name: "отруби овсяные", aliases: ["овсяные отруби"], category: "dessert", kcal: 246, protein: 17, fat: 7, carbs: 66, source: "USDA" },
  { id: "pishchevye_drozhzhi", name: "пищевые дрожжи", aliases: ["дрожжи пищевые","nutritional yeast"], category: "dessert", kcal: 325, protein: 50, fat: 5, carbs: 35, source: "USDA" },
  { id: "zhelatin", name: "желатин", aliases: ["желатин пищевой"], category: "dessert", kcal: 335, protein: 87, fat: 0.4, carbs: 0, source: "USDA" },
  { id: "krakhmal_kartofelnyy", name: "крахмал картофельный", aliases: ["крахмал картофельный","картофельный крахмал"], category: "dessert", kcal: 333, protein: 0.1, fat: 0.1, carbs: 83, source: "USDA" },
  { id: "krakhmal_kukuruznyy", name: "крахмал кукурузный", aliases: ["кукурузный крахмал","крахмал кукурузный"], category: "dessert", kcal: 381, protein: 0.3, fat: 0.1, carbs: 91, source: "USDA" },
  { id: "rassolnik", name: "рассольник", aliases: ["рассольник с перловкой"], category: "side", kcal: 55, protein: 3.5, fat: 2.5, carbs: 5.5, source: "manual_review" },
  { id: "solyanka", name: "солянка", aliases: ["солянка сборная","солянка мясная"], category: "side", kcal: 65, protein: 4.5, fat: 4, carbs: 3.5, source: "manual_review" },
  { id: "uha", name: "уха", aliases: ["уха из рыбы","рыбная уха"], category: "side", kcal: 48, protein: 5, fat: 2, carbs: 2, source: "manual_review" },
  { id: "sup_gribnoy", name: "суп грибной", aliases: ["грибной суп","суп из грибов"], category: "side", kcal: 40, protein: 2.5, fat: 2, carbs: 4, source: "manual_review" },
  { id: "sup_ovoshchnoy", name: "суп овощной", aliases: ["овощной суп","суп из овощей"], category: "side", kcal: 35, protein: 1.5, fat: 1.5, carbs: 5, source: "manual_review" },
  { id: "sup_pyure_tykvennyy", name: "суп-пюре тыквенный", aliases: ["тыквенный суп-пюре","крем-суп тыквенный"], category: "side", kcal: 45, protein: 1.5, fat: 2.5, carbs: 5.5, source: "manual_review" },
  { id: "krem_sup_gribnoy", name: "крем-суп грибной", aliases: ["грибной крем-суп","крем суп грибной"], category: "side", kcal: 55, protein: 2.5, fat: 4, carbs: 4, source: "manual_review" },
  { id: "risotto", name: "ризотто", aliases: ["ризотто с грибами","ризотто классическое"], category: "side", kcal: 130, protein: 4, fat: 4, carbs: 20, source: "USDA" },
  { id: "pasta_bolognese", name: "паста болоньезе", aliases: ["болоньезе","спагетти болоньезе","паста с болоньезе"], category: "side", kcal: 150, protein: 7, fat: 5, carbs: 20, source: "USDA" },
  { id: "pasta_carbonara", name: "паста карбонара", aliases: ["карбонара","спагетти карбонара"], category: "side", kcal: 180, protein: 8, fat: 9, carbs: 18, source: "USDA" },
  { id: "lasagna", name: "лазанья", aliases: ["лазанья мясная","лазанья с мясом"], category: "side", kcal: 135, protein: 7, fat: 6, carbs: 14, source: "USDA" },
  { id: "vareniki_s_tvorogom", name: "вареники с творогом", aliases: ["вареники творожные","вареники с творогом сладкие"], category: "side", kcal: 195, protein: 8, fat: 4, carbs: 32, source: "manual_review" },
  { id: "manti", name: "манты", aliases: ["манты с мясом"], category: "side", kcal: 220, protein: 10, fat: 10, carbs: 24, source: "manual_review" },
  { id: "khinkali", name: "хинкали", aliases: ["хинкали с мясом","хинкали грузинские"], category: "side", kcal: 235, protein: 11, fat: 11, carbs: 24, source: "manual_review" },
  { id: "farshirovannyy_perets", name: "фаршированный перец", aliases: ["перец фаршированный","перец с фаршем"], category: "side", kcal: 120, protein: 6, fat: 6, carbs: 10, source: "manual_review" },
  { id: "kotleta_po_kievski", name: "котлета по-киевски", aliases: ["котлета киевская","киевская котлета"], category: "protein", kcal: 260, protein: 18, fat: 17, carbs: 10, source: "manual_review" },
  { id: "frikadelki", name: "фрикадельки", aliases: ["фрикадельки мясные","фрикадели"], category: "protein", kcal: 200, protein: 14, fat: 12, carbs: 8, source: "manual_review" },
  { id: "zapekanka_tvorozhnaya", name: "запеканка творожная", aliases: ["творожная запеканка","запеканка из творога"], category: "side", kcal: 180, protein: 10, fat: 7, carbs: 20, source: "manual_review" },
  { id: "sushi", name: "суши", aliases: ["суши сет","суши роллы"], category: "side", kcal: 150, protein: 6, fat: 3, carbs: 25, source: "manual_review" },
  { id: "rolly", name: "роллы", aliases: ["ролл","суши ролл"], category: "side", kcal: 155, protein: 6, fat: 4, carbs: 24, source: "manual_review" },
  { id: "roll_philadelphia", name: "ролл филадельфия", aliases: ["филадельфия","ролл с лососем","филадельфия ролл"], category: "side", kcal: 170, protein: 7, fat: 6, carbs: 22, source: "manual_review" },
  { id: "roll_california", name: "ролл калифорния", aliases: ["калифорния","калифорния ролл"], category: "side", kcal: 160, protein: 6, fat: 5, carbs: 23, source: "manual_review" },
  { id: "cheeseburger", name: "чизбургер", aliases: ["бургер с сыром","чиз бургер"], category: "side", kcal: 310, protein: 18, fat: 17, carbs: 25, source: "USDA" },
  { id: "naggetsy", name: "наггетсы", aliases: ["наггетсы куриные","куриные наггетсы","чикен наггетсы"], category: "side", kcal: 280, protein: 14, fat: 17, carbs: 18, source: "USDA" }
];

if(typeof window.validateFoodDB === "function"){
  const check = validateFoodDBItems(window.foodDB);
  if(!check.ok && typeof console !== "undefined" && console.error){
    console.error("foodDB validation failed:", check.errors);
  }
}
